### ISSUE TITLE
Add object functions

### ISSUE THREAD

**Issue by ziflex** [MontFerret/ferret#10]
- [x] KEYS(object, sort) → strArray
- [x]  HAS(object, keyName) → isPresent
~~LENGTH(object) → count~~ ([Implemented here](https://github.com/MontFerret/ferret/blob/master/pkg/stdlib/collections/length.go#L10))
- [x]  MERGE(object1, object2, ... objectN) → newMergedObject
- [x]  MERGE_RECURSIVE(object1, object2, ... objectN) → newMergedObject
- [x]  VALUES(document, removeInternal) → anyArray
- [x]  ZIP(keys, values) → newObj
- [x] KEEP(object, key1, key2, ... key) → newObj

**Comment by 3timeslazy** [comment]
I wanted to work on this issue. If there is any useful additional information - I will be glad to know it.

**Comment by ziflex** [comment]
@3timeslazy great!

1. Read [the documentation](https://docs.arangodb.com/3.4/AQL/Functions/Document.html)
2. Do not implement those methods that are related to ArangoDB Collections like ``IS_SAME_COLLECTION``, ``PARSE_IDENTIFIER`` and etc.
3. Do not mutate values itself - return only new instances.
4. Here is [an example](https://github.com/MontFerret/ferret/tree/master/pkg/stdlib/strings) how to create function. I will merge my work on Array functions, that will be even better reference.

**Comment by 3timeslazy** [comment]
I understand correctly that function KEYS the same with ATTRIBUTES function from the doc? 
https://docs.arangodb.com/3.4/AQL/Functions/Document.html#attributes
First of all, Im interesting in the sort argument. Does it have the same purpose?

**Comment by ziflex** [comment]
@3timeslazy you are right. Pretty much the same.

**Comment by 3timeslazy** [comment]
link inside https://github.com/MontFerret/ferret/issues/10#issue-361404327 is no longer valid.

**Comment by ziflex** [comment]
@3timeslazy updated.

**Comment by 3timeslazy** [comment]
Question about the MERGE function. The documentation supports 2 function signatures: 
1. MERGE(object1, object2, ... objectN) → mergedObject
2. MERGE(objArray) → mergedObject

 In this case need to implement only one (1th signature) or both?

**Comment by ziflex** [comment]
@3timeslazy let's implement both.
Just do a check for a type when you deal with an array.
Which means if any of an array elements is not an object - return ``None``.

Here is ArangoDB's behavior.
<img width="1458" alt="screenshot 2018-10-07 18 06 54" src="https://user-images.githubusercontent.com/1607148/46587530-dd64b700-ca5b-11e8-9aeb-96a61941db69.png">

**Comment by 3timeslazy** [comment]
OK no problem :)

**Comment by 3timeslazy** [comment]
Question about ```VALUES``` function. There is optional parameter ```removeInternal``` into the [doc](
https://docs.arangodb.com/3.4/AQL/Functions/Document.html#values) that responsible for the internal keys (they start with ```_```, such as _id, _key etc.). It is necessary to implement it or not?

**Comment by 3timeslazy** [comment]
How AQL works?
1th query
<img width="354" alt="screenshot 2018-10-15 at 02 49 04" src="https://user-images.githubusercontent.com/23486601/46923735-f4d80d00-d024-11e8-9062-df8bccd6fd07.png">
2th query
<img width="347" alt="screenshot 2018-10-15 at 02 48 45" src="https://user-images.githubusercontent.com/23486601/46923738-fb668480-d024-11e8-8141-12b780044af1.png">
3th query
<img width="405" alt="screenshot 2018-10-15 at 02 47 45" src="https://user-images.githubusercontent.com/23486601/46923753-38327b80-d025-11e8-8122-7e79708680ff.png">

**Comment by ziflex** [comment]
Looks good. 
So, Ferret has some differences how it works.
So, one of them is that RETURN statement in FQL returns expression result as it is.
Contrary to that, RETURN statement in AQL returns an expression result in array.

Maybe it was not a good decision to change the behavior but that’s how it is now.
