### ISSUE TITLE
Add FMT function

### ISSUE THREAD

**Issue by ziflex** [MontFerret/ferret#106]
Add ``FMT(template, values)`` function that would replace placeholders with given values.

Example:

```
FOR idx IN 1..10
    LET selector = FMT("div.panel-group table tr:nth-child({})", idx)
    RETURN INNER_TEXT(selector)
```

I think [Rust implementation](https://doc.rust-lang.org/std/fmt/) might be more useful for this project, than Go's one.

Especially, ability to reuse parameters using their indexes.
```
format!("{1} {} {0} {}", 1, 2); // => "2 1 1 2"
```

**Comment by 3timeslazy** [comment]
It's possible to reuse parameters by their name using Go's templates. Ex
```go
{{ .P1 and .P1 and .P2 }}
```

**Comment by ziflex** [comment]
@3timeslazy you are right. Forgot about templates. Have never used them 🤔
Do we need these curly brackets?

**Comment by ziflex** [comment]
@3timeslazy do you wanna take this one?

**Comment by 3timeslazy** [comment]
@ziflex sure.

**Comment by 3timeslazy** [comment]
As far as I understand, the signature of the FMT function is:
```go
func FMT(tmpl string, args ...core.Value)
```

**Comment by ziflex** [comment]
@3timeslazy yup, looks good!

**Comment by ziflex** [comment]
@3timeslazy hey, any updates on this?
