### ISSUE TITLE
Go Best Practise: comments

### ISSUE THREAD

**Issue by 3timeslazy** [MontFerret/ferret#110]
I want to suggest writing comments for functions in the style of Go Best Practices. Ex.:
comments now:
```go
/*
 * Returns the value stored by the given key.
 * @params (String) - The key name string.
 * @returns (Boolean) - True if the key exists else false.
 */
func Has(_ context.Context, args ...core.Value) (core.Value, error) {
    // code
}
```
Go Best Practise:
```go
// Has returns the value stored by the given key.
// @params (String) - The key name string.
// @returns (Boolean) - True if the key exists else false.
func Has(_ context.Context, args ...core.Value) (core.Value, error) {
    // code
}
```

**Comment by ziflex** [comment]
Ahhh comments, sure. 
Shame on my that I didn't start writing them in idiomatic way from the beginning.

Ideally, I need to comment all exported methods and functions...

**Comment by 3timeslazy** [comment]
@ziflex I can rewrite old ones, it does not look difficult.

**Comment by ziflex** [comment]
That would be great!

**Comment by ziflex** [comment]
@davad here is his [PR](https://github.com/MontFerret/ferret/pull/118).
But you can cover those parts that do not have comments at all, if you want to :)
