### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by ziflex** [MontFerret/ferret#112]
Ok, as more Ferret becomes stable and featureful, more I think about its server side.

Before I jump on its implementation I would like to share some ideas about features I want and I think might be useful. Also, there are some questionable ideas that I would like to discuss with somebody :)

So, here is a list of must-have features:
#### Projects
The way how to group and isolate scripts and their results. Having different projects would allow us to easier organize content of the server.

#### Scripts persistence
Pretty straightforward and basic - I want to store my scripts on server.

#### Scripts scheduling
Be able to schedule scripts. 
By default, I think we can just trigger a script by calling a certain API endpoint (like, ``/runtime/start/:scriptID``)
In contrast to that, scheduling would allow us to automate this process, by:
- Time scheduling
- Web Hook scheduling 

#### Results persistence
By default, we would persist results from all scripts in one single collection.
Additionally, there is an idea of an option to create a dedicated collection for a specific script, in order to avoid having one huge collection with very different data.
- Default collection
- Dedicated collection

#### Results output stream
Also, it might be pretty useful, not to store the results locally, but send them to another service like Spark or Flink instead.
That means, that we need to provide custom service clients.
So, at this point we have more options what to do with the data, by choosing output:

* Local persistence
    - Default collection
    - Dedicated collection
* Remote persistence
    - Spark
    - Flink
    - etc

#### Data validation
Optionally, we could define JSON Schema to validate script results.

#### Scripts search
This is a draft idea. It supposes having a **FQL Registry** like ``NPM``, where people could share scripts and version them.
So, instead of writing scripts manually, we could just find them and install on our server.

#### Authentication
Optional token based authentication.

Any thoughts?

**Comment by ziflex** [comment]
@davad that's really interesting idea. 
How would you retrieve data from it? Using ``AQL``?
In the very beginning of the project, I was thinking of having 2 languages: 1 is for web scraping (A/FQL) and another one for querying the results. So, this idea supposed to use GraphQL as a language for querying the results and multiple FQL scripts could be used as query resolvers.

**Comment by davad** [comment]
AQL or GraphQL both make a lot of sense. GraphQL sounds particularly interesting, since if you expose a public GraphQL endpoint, you could have SPAs query ferret directly.

**Comment by ziflex** [comment]
Created tasks in the corresponding repo.
