### ISSUE TITLE
WaitForNavigation callback can get called more than once.

### ISSUE THREAD

**Issue by ap0** [MontFerret/ferret#125]
**Describe the bug**
The callback in WaitForNavigaton can get called more than once, causing a panic due to closing a channel that is used to signal the page load event closing again.

**To Reproduce**
Not able to reproduce consistently.

**Expected behavior**
Should remove the handler from the page load event and not call the callback more than once.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 69

**Additional context**
https://github.com/MontFerret/ferret/pull/96

**Comment by ziflex** [comment]
[Some work in this area](https://github.com/MontFerret/ferret/blob/refactoring/new-event-broker/pkg/html/dynamic/events/broker.go).
It should fix it. It's almost done, I just need to write some unit tests.
Hope, it will solve this and race condition problems.

**Comment by ziflex** [comment]
@ap0 re-open it, please, if it happens again after this merge.

**Comment by ap0** [comment]
I ran into this bug again.

The issue happens on a page that does a bunch of really quick redirects for some SSO login stuff.  Seems to be the same thing as before.

I was able to get around it modifying `WaitForNavigation` and putting the `close(onEvent)` in a `sync.Once`.

```
func (doc *HTMLDocument) WaitForNavigation(ctx context.Context) error {
	onEvent := make(chan struct{})
	var once sync.Once
	listener := func(_ context.Context, _ interface{}) {
		once.Do(func() {
			close(onEvent)
		})
	}

```

Happy to submit a PR with this.

**Comment by ap0** [comment]
@ziflex I can't re-open this since I didn't close but wanted to bring to your attention.
