### ISSUE TITLE
Rename DOCUMENT() to PAGE() or URL()?

### ISSUE THREAD

**Issue by ziflex** [MontFerret/ferret#130]
In context of work on Ferret Server, I came up with an idea to let Ferret scripts give an optional access to the underlying database (limited access granted by a creator and only to certain types of collections).
But the problem is that DOCUMENT function name exists in both AQL and FQL but do different things. As a result we have a name collision.
I see two options here:
- rename Ferret’s DOCUMENT function to something more meaningful and web specific 
- use different function name for database integration

**Comment by 3timeslazy** [comment]
```URL()``` is associated with URL strings like ```http://www.github.com``` or something else. I think ```PAGE()``` is mush better. Also suitable names: ```WEBPAGE()```, ```HTML_DOCUMENT()```, ```LOAD_DOCUMENT()```, ```LOAD_PAGE()``` etc.

**Comment by CodeMedic42** [comment]
If you are using this to access a url would WEBSITE() or SITE() make any sense? What about HTML(), then at some point you could add terms that deal with something other than HTML, like JSON() or XML(). Spitballing here...

**Comment by davad** [comment]
The consensus seems to be to rename Ferret's `DOCUMENT()` to something more meaningful.

I agree with @3timeslazy about `URL()` not being appropriate, but `LOAD_URL()` could work. My favorites so far are `PAGE()`or `LOAD_PAGE()`.

**Comment by ziflex** [comment]
In 0.6.0 ```DOCUMENT``` will be renamed to ```PAGE```.
