### ISSUE TITLE
How to Debug? Any PRINT function or statement?

### ISSUE THREAD

**Issue by gurditsbedi** [MontFerret/ferret#138]
Well, usually people debug using PRINT statements. What is the `print` equivalent in `ferret` ? 
`RETURN` doesn't seem to be helpful much, because I want to print multiple variables, in different segments of the program.

**Comment by gurditsbedi** [comment]
I found `LOG` function, tried it but not getting any output on the terminal.

**Comment by ziflex** [comment]
You can use that LOG function . 
It writes messages into ferret.log file which you can find in your working directory.

**Comment by ziflex** [comment]
Feel free to re-open if you have more questions.
