### ISSUE TITLE
Add DOWNLOAD function

### ISSUE THREAD

**Issue by ziflex** [MontFerret/ferret#14]
Add ``DOWNLOAD(content) -> binary`` function which would download binary data.

**Comment by Pangoraw** [comment]
Hi,

I am thinking about how to implement this feature. The way I see it, is to use chromium to download to a temporary folder (using [this](https://godoc.org/github.com/mafredri/cdp/protocol/page#SetDownloadBehaviorArgs)). And when the download is done, return the binary data from the downloaded file then remove the temporary folder.

Do you see another way ?

**Comment by ziflex** [comment]
@Pangoraw I was thinking of using just plain HTTP client for that.

**Comment by Pangoraw** [comment]
For static document yes, but if you want to scrap documents in dynamic documents which requires authentification (for example), this could not be enough ?

**Comment by ziflex** [comment]
#120
As a reference
