### ISSUE TITLE
Error driver, first launch

### ISSUE THREAD

**Issue by Erim32** [MontFerret/ferret#166]
**Describe the bug**
First usage provide driver error, with generic error message, more details can be appreciate for fix it.

**Screenshots**
![image](https://user-images.githubusercontent.com/8769532/48168384-46577d00-e2ef-11e8-998e-01d586c688ee.png)

**Desktop (please complete the following information):**
 - OS: Win10 1807
 - Browser: Chrome
 - Version: 0.4.0

**Comment by ziflex** [comment]
@Erim32 hey, welcome!
Did you run Chrome with open debug port or headless Chrome in Docker with bound port before running Ferret?

https://github.com/MontFerret/ferret#environment

**Comment by Erim32** [comment]
@ziflex That was a Chrome configuration issue, fixed, 
Thank you
