### ISSUE TITLE
paginate

### ISSUE THREAD

**Issue by wforfun** [MontFerret/ferret#171]
Hi bro, 
Thanks for your effort, this is an awesome project.
I try the crawler paginate page without the next button, Can you give me some suggestion. 
Thank you so much.

**Comment by ziflex** [comment]
@wforfun hey, thank you for your kind word, I'm glad that you like it!
Pagination is a tricky thing, especially when you need to handle it with declarative-ish language like Ferret has.
Could you give me more details how the paginations is implemented?

**Comment by wforfun** [comment]
Thank you for your response. This is example of paginations, it have page number and last button `>`, the next button is missing. 
`<div class="background-pager-right-controls">
	<a href="/n"><div style="" class="style-pager-row-selected" align="center">1</div></a>
	<a href="/n/p2"><div style="" align="center">2</div></a>
	<a href="/n/p3"><div style="" align="center">3</div></a>
	<a href="/n/p2"><div style="" align="center">...</div></a>
	<a href="/n/p10670"><div style="" align="center">&gt;</div></a>
	<span id="ProductsPager"></span>
</div>`

**Comment by ziflex** [comment]
@wforfun 
isn't this element a next button?
```html
<a href="/n/p10670"><div style="" align="center">&gt;</div></a>
```

**Comment by ziflex** [comment]
@wforfun I'm closing it for now. Feel free to re-open it if you have more questions.
