### ISSUE TITLE
How to execute example on Windows (10)?

### ISSUE THREAD

**Issue by namedgraph** [MontFerret/ferret#191]
I tried

    chrome.exe --remote-debugging-port=9222

which launched Chrome, and then

    ferret google.fql
    Failed to execute the query
    failed to initialize driver: Get http://0.0.0.0:9222/json/version: dial tcp 0.0.0.0:9222: connectex: No connection could be made because the target machine actively refused it.: DOCUMENT("https://www.google.com/",true) at 1:13

I also tried

    ferret --cdp-launch
    Welcome to Ferret REPL 0.5.0
    Please use `exit` or `Ctrl-D` to exit this program.

So I got an error in the first case, and nothing happened in the second case. What's wrong?

**Comment by ziflex** [comment]
@namedgraph hey, thanks for giving Ferret a try :)

Try to run CLI with this argument:
```ferret.exe --cdp=http://localhost:9222```

I think the problem is that Windows does not resolve ```0.0.0.0``` address the same way Linux/macOS do.

**Comment by davad** [comment]
I had access to a Windows machine today, so I tried it out. I was able to get it working using the hosts `localhost`, `127.0.0.1` and `0.0.0.0` in the `--cdp` flag. Here's the steps to reproduce what I did:

1. Closed Chrome completely
2. Started Chrome by running `C:\Users\username\AppData\Local\Google\Chrome\Application\chrome.exe --remote-debugging-port=9222`
3. Downloaded and extracted the latest Windows 64-bit release ([v0.5.1](https://github.com/MontFerret/ferret/releases/download/v0.5.1/ferret_windows_x86_64.zip))
4. Downloaded the [dynamic page example](https://github.com/MontFerret/ferret/blob/master/examples/dynamic-page.fql).

With `ferret` and `dynamic-page.fql` in the same directory, I was able to run each of the following from the command prompt:

* `ferret.exe dynamic-page.fql`
* `ferret.exe --cdp=http://0.0.0.0:9222 dynamic-page.fql` 
* `ferret.exe --cdp=http://127.0.0.1:9222 dynamic-page.fql` 
* `ferret.exe --cdp=http://localhost:9222 dynamic-page.fql`

**Comment by ziflex** [comment]
@davad thank you!
