### ISSUE TITLE
Add PDF function

### ISSUE THREAD

**Issue by ziflex** [MontFerret/ferret#20]
Add a function which converts an open page into PDF and returns it as binary data.

The method is supposed to be handled by ``dynamic`` web driver.
There are two signatures:

``PDF(document) -> binary``
and 
``PDF(url) -> binary``

and it should use ``cdp`` client API.

**Comment by zhichuanxun** [comment]
Can I use other packages on GitHub such as [gofpdf](https://github.com/jung-kurt/gofpdf)?
Sorry for asking such a stupid question. I am a rookie to GitHub, but I am willing to do some contributes.

**Comment by ziflex** [comment]
@zhichuanxun hey, I updated the task with more description. This functionality must be implemented by Chrome DevTools Protocol client that Ferret relies on and only applicable to dynamic pages.

**Comment by zhichuanxun** [comment]
@ziflex Sorry for having no ability to help. I need to study more for a while. Maybe next time I can make some contributions.

**Comment by ziflex** [comment]
@zhichuanxun that's fine, you are always welcome :)
