### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by ziflex** [MontFerret/ferret#208]
Create a website with nice and clean design.
It should contain:

- [ ] Introduction
- [ ] Quick start
- [ ] Guideline
- [ ] API documentation
- [ ] FAQ (?)
- [ ] Contact information

The website repo is [here](https://github.com/MontFerret/website).

**Comment by ziflex** [comment]
Good example:
http://go-colly.org/

**Comment by guylyons** [comment]
Hey, definitely interested in working on this. I can start with wireframes or just jump right into theming similar to Colly. And will build out in Hugo. Thanks.

**Comment by ziflex** [comment]
@guylyons hey, that would be fantastic! Thank you!

**Comment by guylyons** [comment]
np! I've forked and started scaffolding the theme. Matching up w/ the purples used in your art. Should have a rough soon to share.

**Comment by guylyons** [comment]
@ziflex Here's a rough version of where I've got this theme built out. Most pages are not templated out completely, more for example and experimenting. Let me know your thoughts here, and if you'd like to layout content differently at all.

I figured most pages would be simple 1-column layout, but FAQs and API would probably require some sort of aside for navigating through sub topics.

[Here's a demo instance](https://vibrant-euclid-cf9207.netlify.com/) on Netlify.

**Comment by 3timeslazy** [comment]
We need a section with contributors!

**Comment by davad** [comment]
@guylyons That looks really good! My only feedback is the logo needs a little more space between the image and the text. Somewhere between 0.3 em and 0.5 em, I think.

**Comment by ziflex** [comment]
@guylyons hey, that's awesome! I love it!    

There are some things related to navigation I think we need to improve like merging ``Quick start`` and ``Guidelines`` together and adding ``Contact us``

**Comment by guylyons** [comment]
@ziflex glad to hear! I'll clean up the nav and adjust the logo. Would you see `Quick Start` and `Guidelines` as siblings of something like `Docs` for the parent item? Thanks.

**Comment by ziflex** [comment]
@guylyons I was thinking of making ``Guidelines`` as a parent section which contains ``Quick Start / Getting Started``, ``Installation`` and etc.
I like how it's organized on this website: https://rocket.rs/v0.4/guide/ (The website is done very well in general).

Additionally to that, we may add ``Community`` section with links to Discord channel, GitHub issues page and some _Join Us_ text.

Do we need ``News`` section like Rocket has?

**Comment by guylyons** [comment]
@ziflex That looks great, I like the layout. I think adding `News` would be a nice place for milestones and announcements. Will have more updates soon.

**Comment by ziflex** [comment]
Hey @guylyons, maybe we could merge your changes with the corresponding repo?
In this case we all could start working on it :)

**Comment by guylyons** [comment]
@ziflex -- of course! Just submitted the PR.

**Comment by ziflex** [comment]
@guylyons great! Thank you for your help!

I'm closing the issue. All future issues should be open in [the corresponding repo](https://github.com/MontFerret/website/issues).

**Comment by ziflex** [comment]
@guylyons hey, I messed up with deployment settings (haven't used Hugo before) and had to nuke the repo and recreate it. Sorry for the lost PR.

**Comment by guylyons** [comment]
@ziflex no worries. Were you able to figure out deploy? Here's the docs for Hugo w/ GitHub Pages method: https://gohugo.io/hosting-and-deployment/hosting-on-github/

You'll want to replace my Netlify URI in the root config.toml.

**Comment by guylyons** [comment]
hey @ziflex just realized the commit history was wiped -- any chance you can create it again as an empty repo and I can resubmit that PR? Would like to keep my contrib history in there if possible.

**Comment by ziflex** [comment]
> @ziflex no worries. Were you able to figure out deploy? Here's the docs for Hugo w/ GitHub Pages method: https://gohugo.io/hosting-and-deployment/hosting-on-github/
> 
> You'll want to replace my Netlify URI in the root config.toml.

Almost :) I messed up with a submodule for ``public`` folder. By some reason all content went into root folder.

> hey @ziflex just realized the commit history was wiped -- any chance you can create it again as an empty repo and I can resubmit that PR? Would like to keep my contrib history in there if possible.

Sorry for that. I recreated, you can submit the PR.

**Comment by ziflex** [comment]
@guylyons done!

**Comment by guylyons** [comment]
@ziflex thanks. You'll need to commit a readme or just any single file so I can fork the repo.
