### ISSUE TITLE
Add SCREENSHOT function

### ISSUE THREAD

**Issue by ziflex** [MontFerret/ferret#21]
Add a functions which takes a screenshot of the open page and returns it as binary data.

**Comment by Pangoraw** [comment]
I had like to implement this feature.
The signature would be :
```aql
SCREENSHOT(document, x, y, height, width, format, quality)
```
Or something like that ?

**Comment by Pangoraw** [comment]
`PrintToPDF` has as much as 15 arguments ( for #20 ), maybe I could use an object to pass them, so the signatures would look like :
```
SCREENSHOT(document, screenshotParams)
PDF(document, pdfParams)
```

**Comment by ziflex** [comment]
@Pangoraw sounds good!

I was thinking of two signatures:

``SCREENSHOT(document[, params]) -> binary``
and 
``SCREENSHOT(url[, params]) -> binary``

same with ``PDF```.

The url option can be used as a shortcut with a Chrome tab which has a short life span, when you just need a screenshot or PDF. By short living I mean, you would just open the document, take a screenshot or PDF and close it after that.
