### ISSUE TITLE
CSV output

### ISSUE THREAD

**Issue by namedgraph** [MontFerret/ferret#216]
Is there a way to get the output as CSV instead of JSON?

**Comment by ziflex** [comment]
At this moment, CLI outputs data only in JSON format.
You can wrap Ferret lib with your own CLI that would convert JSON into CSV.
[Here](https://github.com/MontFerret/ferret/blob/master/examples/embedded.go) you can see learn how to use Ferret as a library.

**Comment by ziflex** [comment]
@namedgraph we can add an optional flag to CLI to transform JSON output to CSV format.

**Comment by namedgraph** [comment]
I wonder if the output data structure is always strictly tabular?
If that is the case, I would argue CSV makes more sense as the default format.
If not, then CSV might be problematic for fields with multiple values. That could become duplicated columns in a table, but then it's not standard CSV really.

**Comment by ziflex** [comment]
@namedgraph output data structure is arbitrary.
```sh
> RETURN 1
> 1
```

```sh
> RETURN { foo: "bar"}
> { "foo": "bar" }
```

```sh
> RETURN { foo: { bar: "baz" } }
> { "foo": { "bar": "baz" } }
```

End so on.

**Comment by ziflex** [comment]
I'm closing it. Feel free to re-open, if you have any questions.
