### ISSUE TITLE
Can ferret dsl work with chromedp?

### ISSUE THREAD

**Issue by kaixinbuyu** [MontFerret/ferret#224]
I have some old source code on top of chromedp:"github.com/chromedp/chromedp".And I want to move to ferret.
Can ferret dsl (with some migrate)work with chromedp()?
currently ferret works with "github.com/mafredri/cdp",difficult on proxy,cluster,chromedp is much easyier.

What's the most reason choosing "github.com/mafredri/cdp" better than chromedp?

**Comment by ziflex** [comment]
The main reason why ```github.com/mafredri/cdp``` was chosen is that it supports multiple tabs. 
When```github.com/chromedp/chromedp``` works with one single tab (you can see [here](https://github.com/chromedp/chromedp/issues/232), [here](https://github.com/chromedp/chromedp/issues/228) and [here](https://github.com/chromedp/chromedp/issues/170)) and does not allow you to utilize single Chrome instance for multiple queries.

Proxy and clustering is operational responsibility and have nothing to the client. Moreover, you cannot setup a proxy when Chrome is already running, you can only set it during its launch.

And in general, ```github.com/mafredri/cdp``` is very stable library, didn't have any issues so far.

**Comment by kaixinbuyu** [comment]
thank you very much!

**Comment by tmm1** [comment]
FYI chromedp v0.2.0 now supports multiple tabs: https://github.com/chromedp/chromedp/issues/228#issuecomment-478948635
