### ISSUE TITLE
get element by innerText

### ISSUE THREAD

**Issue by kaixinbuyu** [MontFerret/ferret#225]
Element selector is important in crawler.

As for all selector is got by "document.querySelector",
it does not support get element by innerText like jquery or xpath:
.click('//a[contains(@class, "tree")
.click('//a[contains(text(), "tree")

currently I modified the code:

eval.Eval(
		doc.client,
		fmt.Sprintf(`
			var el = document.querySelector(%s);

and write custom javascript to archive this.

Is there other sample way to do this?how to enhance the default selector?

**Comment by ziflex** [comment]
@kaixinbuyu hi, thank you for giving Ferret a try!

Could you provide more details on what you are trying to do?

There are bunch of functions that accept CSS selectors.

**Comment by kaixinbuyu** [comment]
locate and click the next element by innerText only,no id,no class:
<a href="2.html">Next</a>

.click('//a[contains(text(), "Next")

**Comment by kaixinbuyu** [comment]
thanks！
