### ISSUE TITLE
can not reach the element

### ISSUE THREAD

**Issue by eruca** [MontFerret/ferret#226]
**Describe the bug**
I want to reach one element in the HTML page, but the result return none;

```go
query := `
	LET doc = DOCUMENT("http://zhwzbjjyx.yiigle.com/gkmc/index.htm", true)

	LET title = WAIT_ELEMENT(doc, '.Index_Title', 5000)

	LET span = ELEMENT(title, 'span')

	RETURN span.innerText
	`
	comp := compiler.New()

	program, err := comp.Compile(query)
	if err != nil {
		return nil, err
	}

	ctx := context.Background()

	ctx = drivers.WithDynamic(ctx, cdp.NewDriver())
	ctx = drivers.WithStatic(ctx, http.NewDriver())

	out, err := program.Run(ctx)
	if err != nil {
		panic(err)
	}

```

**Expected behavior**
panic: invalid type: expected HTMLDocument or HTMLElement, but got none: ELEMENT(title,'span') at 6:12

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.2
 - Browser chrome
 - Version 71.0.3578.98 64bit

**Comment by ziflex** [comment]
@eruca hi, thank you for giving Ferret a try!

What you are trying to do is little bit wrong, but an interesting idea, I might consider to add.

The issue is ```WAIT_ELEMENT``` does not return an element. It just blocks an execution until an element appears by a given selector (or operation times out).
Therefore, in order to make your script work, you need to add ```ELEMENT``` function:

```
query := `
	LET doc = DOCUMENT("http://zhwzbjjyx.yiigle.com/gkmc/index.htm", true)

        WAIT_ELEMENT(doc, '.Index_Title', 5000)
	LET title = ELEMENT(doc, '.Index_Title')

	LET span = ELEMENT(title, 'span')

	RETURN span.innerText
	`
	comp := compiler.New()

	program, err := comp.Compile(query)
	if err != nil {
		return nil, err
	}

	ctx := context.Background()

	ctx = drivers.WithDynamic(ctx, cdp.NewDriver())
	ctx = drivers.WithStatic(ctx, http.NewDriver())

	out, err := program.Run(ctx)
	if err != nil {
		panic(err)
	}
```

**Comment by eruca** [comment]
I fixed it, thanks.
