### ISSUE TITLE
Set and Get Cookies

### ISSUE THREAD

**Issue by advancedlogic** [MontFerret/ferret#236]
In case of login into a website it would be helpful to get the cookies and reuse them to control the session (avoiding to login every time)

**Comment by ziflex** [comment]
@advancedlogic currently Ferret uses Incognito window for each request, that's why none of data gets persisted. But it should be okay in between transitions within a single query.

We might consider to pass extra params to the CDP driver in order to change the behavior and use regular windows.
But Incognito mode will remain as a default one.

**Comment by advancedlogic** [comment]
I understand the incognito mode’s choice but it would be great to set cookies (getting the cookies and storing them somewhere after the 1st login)to avoid logging in every time  with the risk of being banned.

**Comment by ziflex** [comment]
@advancedlogic hey, the cookie support has landed on master branch.
Here are example how you can use them:

```
LET doc = DOCUMENT(@url, {
    driver: "cdp",
    cookies: [{
        name: "x-e2e",
        value: "test"
    }]
})

```

```
LET doc = DOCUMENT(@url, {
    driver: "cdp"
})

COOKIE_SET(doc, {
    name: "x-e2e",
    value: "test"
})
```

```
LET doc = DOCUMENT(@url, {
    driver: "cdp"
})

LET cookie = COOKIE_GET(doc, "x-ferret")
LET cookie_2 = doc.cookies
```

```
LET doc = DOCUMENT(@url, {
    driver: "cdp",
    cookies: [{
        name: "x-e2e",
        value: "test"
    }, {
        name: "x-e2e-2",
        value: "test2"
    }]
})

COOKIE_DEL(doc, COOKIE_GET(doc, "x-e2e"), "x-e2e-2")
```

**Comment by ziflex** [comment]
Let me know how it works in your case. I would like to make it stable for v0.7 release.

**Comment by advancedlogic** [comment]
thanks :)
