### ISSUE TITLE
what's the syntax of AQL of passing long complex string?

### ISSUE THREAD

**Issue by kaixinbuyu** [MontFerret/ferret#243]
I write a custom function RUN_JAVASCRIPT by comp.RegisterFunction,and when I what to invoke it in AQL script like this:

_LET google = DOCUMENT("https://www.google.com/", true)
INPUT(google, 'input[name="q"]', "ferret", 25)
CLICK(google, 'input[name="btnK"]')
**RUN_JAVASCRIPT**(doc,`...........**complex javascritpt string contains ",',\,(,),;\n or other letters**.............`)_

I tried convert ' ==> \\' ,  " => \\"  at AQL's document but it doesn't work.
How to pass the right string to the function?Is there other similar case to reference?

**Comment by ziflex** [comment]
Hi, thanks for giving Ferret a try!

Did you try to use ` symbol for strings? 
Also, it would be more helpful if you provided the code snippet.

**Comment by kaixinbuyu** [comment]
Thank you! I try to use  ` symbol for strings and it works!like the code in package:

func ParamString(param string) string {
	return "`" + param + "`"
}
