### ISSUE TITLE
how to setup a multi-tenant chrome downloader for multi-users?

### ISSUE THREAD

**Issue by kaixinbuyu** [MontFerret/ferret#248]
1.In my case I want to run multi-user's chrome url requests.
**requests between users should be separated even it is the same url as they have different password and web content.** eg:
user1 use uname1,passwd1 login to www.ajax-page.com and take snapshot ,save png to user1's store;
user2 use uname2,passwd2 login to www.ajax-page.com  and take snapshot ,save png to user2's store;

2.what I have tested is:
for separate cookie env,I have to lunch different chrome instance for each user.
create a map[user-id]*ferret-connect to->different chrome instance at different port. eg:
user1 use uname1,passwd1 login to www.ajax-page.com running on ferret1-conn-to-chrome[:9222]
user2 use uname2,passwd2 login to www.ajax-page.com running on ferret2-conn-to-chrome[:9223]

3.the question is that I found only one chrome can be lunched. othe chromes are failed:
dial tcp [::1]:9223: connectex: No connection could be made because the target machine actively refused it.","driver":"dynamic","message":"failed to initialize the driver"}
 
4.So what's the right way to do this?maybe I do not need to lunch diferent chrome instance for each user.I'm not sure of this.

**Comment by ziflex** [comment]
That's a good use case! Ideally, you need to wait for [this PR get merged](https://github.com/MontFerret/ferret/pull/242).
But, alternatively, you should be able to launch Chrome with separate user dir for each query.

> 3.the question is that I found only one chrome can be lunched. othe chromes are failed:
> dial tcp [::1]:9223: connectex: No connection could be made because the target machine actively refused it.","driver":"dynamic","message":"failed to initialize the driver"}

How do you launch it? Just as an app or a Docker container?
Docker container should work flawlessly.

**Comment by kaixinbuyu** [comment]
Lunch as an golang app.
I'll try separate user dir first,thank you very much!

**Comment by kaixinbuyu** [comment]
_But, alternatively, you should be able to launch Chrome with separate user dir for each query._

separate user dir,It works!thank you!
