### ISSUE TITLE
help to solve:DOM.resolveNode" rpc error: Node with given id does not belong to the document (code = -32000)

### ISSUE THREAD

**Issue by kaixinbuyu** [MontFerret/ferret#252]
I found in some rare case(1/5~),my golang app lunch a chrome.exe[9222] like the code in ferret-cli,
when run into "DOCUMENT"(LET doc = DOCUMENT(%v,true)) function:

_broker, err := createEventBroker(client)

	if err != nil {
		handleLoadError(logger, client)
		return nil, errors.Wrap(err, "failed to create event events")
	}

	rootElement, err := **LoadElement**(
		ctx,
		logger,
		client,
		broker,
		node.Root.NodeID,
		node.Root.BackendNodeID,
	)
obj, err := client.DOM.ResolveNode(ctx, args)
err = rpcc.Invoke(ctx, "DOM.resolveNode", args, reply, d.conn)_

"DOM.resolveNode" method returned an error message :
**rpc error: Node with given id does not belong to the document (code = -32000)**

But keep the same golang app running,run the second,third time...same workflow again:lunch chrome.exe[9222],run the same LET doc = DOCUMENT(%v,true)) script,No errors occur!

The page is loaded and rendered out successfuly as I can see in chrome.exe.

The target site is an ajax site,it's slow to visit in some times.Maybe this is another factor.

It's hard to debug this error as It occurs rarely and breakpoint slowdown the commucation of websocket of chrome may make other influnce.

As the error message shows:**"DOM.resolveNode" rpc error: Node with given id does not belong to the document (code = -32000)** shows,Is there any suggestions to do with this bug?

**Comment by ziflex** [comment]
Hi @kaixinbuyu!
Interesting error. I have never experienced that, but I assume that at some point your page performs a navigation to another document, and all retrieved nodes before, become obsolete since they are not longer part of a new document.

**Comment by kaixinbuyu** [comment]
I have the same opinion.
Is there any method(+javascript,not only ferret script.) to "lock"(prevent navigation) a document(disable navigation to others) while retrieving document.outerhtml,"release" the document lock and ajax click to next page?

**Comment by ziflex** [comment]
You may try some methods from [``cdp.Network``](https://godoc.org/github.com/mafredri/cdp#Network) sub-package like ``SetRequestInterception`` or use plain JS approach with ``window.onbeforeunload`` event handler blocking page navigation.

**Comment by kaixinbuyu** [comment]
After debug the detail send/rcv log of websocket,I find out the err is caused by url redirecting.
The crude solution is modify the LoadElement function to wait one second and retry 3 times.
Thank you!
