### ISSUE TITLE
how to write AQL loop with break?

### ISSUE THREAD

**Issue by kaixinbuyu** [MontFerret/ferret#253]
I have read the arangodb 's document and do not find a example to do this:

```
FOR navNum IN 1..10000  //in fact I mean infinite loop,I'm not sure write a collection read from chan is workable.

  LET url = FETCH_A_NAVIGATE_URL_FROM_CHAN() //a registed udf returning a url string "www.abc.com..." or "" string by select from a go chan;if the chan is empty,the default case returns ""

  LET is_valid_url = url != ""? true : return false // error here. I want to break the loop if url == "",how to write this?

  LET doc = DOCUMENT(url,true)
   ...//the following is the same as noraml
```

the FETCH_A_NAVIGATE_URL_FROM_CHAN is a  sample select:

```
navigate_url := ""
select {
		case req,ok := <-page_navigate_request_pool:
			if ok {
				navigate_url = req.Url
			}
		default:
			dl.logger.Debugf(">>fetch url empty!quit navigateion...[%v][%v]...",page_num,navigate_url)
		}
return values.NewString(navigate_url),nil
```

the main idea is that I want to keep nav url dynamicly by push url to a  go chan.because the url array is generated dynamicly and synchronously,not a fixed url array like the noraml example.

**Comment by ziflex** [comment]
I'm afraid, you cannot do that.

If you are using Ferret v0.6, your function can return a custom user type which implements [```IterableCollection ```](https://github.com/MontFerret/ferret/blob/v0.6.0/pkg/runtime/collections/collection.go#L28) and use it as a data source for FOR IN loop. You can take a look how to implement custom type [here](https://github.com/MontFerret/ferret/blob/v0.6.0/pkg/stdlib/html/pagination.go#L39).

Here is an example:

```
FOR url IN FETCH_A_NAVIGATE_URL_FROM_CHAN()
  LET doc = DOCUMENT(url,true)
   ...//the following is the same as noraml
```

But, be aware, that in context of v0.7, the interface was [moved](https://github.com/MontFerret/ferret/blob/master/pkg/runtime/core/value.go#L22) and type system [changed](https://github.com/MontFerret/ferret/blob/master/pkg/runtime/core/type.go#L13) as well, so you will have to do some little migration.

**Comment by kaixinbuyu** [comment]
Thanks a lot for the troubles you've taken to help me!I will post back if I dind a solution.

**Comment by ziflex** [comment]
> Does AQL support loop break?

No.

> if not,I have to return error if url == "" to break all the program.
> 
> Thanks a lot for the troubles you've taken to help me!I will post back if I find a solution.

If you implement the iterator, the app will finish its execution when the iterator's channel gets exhausted.
[Here is an example](https://play.golang.org/p/HTafqpKFjee).

**Comment by kaixinbuyu** [comment]
the final code solution is as bellow:
raise error if empty url selected from chan.
it works,I'll improve it latter if have time.


```
LET doc = DOCUMENT("about:blank",true)

FOR navNum IN 1..100
  LET url = FETCH_NAVIGATE_URL(navNum)

  NAVIGATE(doc, url)
  WAIT(1000)



select {
		case req,ok := <-page_navigate_request_pool:
			if ok {
				p.logger.Debugf(">>fetch url[%v][%v]...",page_num,req.Url)
				return values.NewString(req.Url),nil
			}
		default:
			p.logger.Debugf(">>fetch url empty!quit navigateion...[%v]...",page_num)
			return values.EmptyString, fmt.Errorf("no navigate url need to run.")
		}
```
