### ISSUE TITLE
FQL WHILE loop

### ISSUE THREAD

**Issue by ziflex** [MontFerret/ferret#262]
Even though, AQL does not support ```WHILE``` loop, there are certain scenarios in scraping, where the loop can be very useful.
Current workaround is to create a custom Iterator, that would do a specific comparison, but it's cumbersome and not straightforward. There should be a better solution.

For inspiration, we can take a look how it's done in [MS SQL](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/while-transact-sql?view=sql-server-2017).

Possible syntax:

```
WHILE el.style.display != "none"
    CLICK(doc, "next")
```

**Comment by ziflex** [comment]
In order to keep syntax clean and less verbose, here is an alternative possible syntax:

```
FOR el.style.display != "none"
    CLICK(doc, “#next”)
    
    RETURN SOMETHING 
```

The main difference here is of course use of an existing keyword with simplified grammar, but with preserved “querying” logic.

You could also use ``LIMIT`` and ``FILTER`` (with outer scope only) statements like with regular ``FOR IN`` loop.

**Comment by PierreBrisorgueil** [comment]
```
FOR el.style.display != "none"
    CLICK(doc, “#next”)    
    RETURN SOMETHING 
```

with filter and limit sound good for me. 

but for alignment, a better understanding of the dev I would stay on that if it is possible

```
WHILE el.style.display != "none"
    CLICK(doc, “#next”)    
    RETURN SOMETHING 
```

Same syntax, more difficult to learn. But a different keyword to characterize the different use cases (easier to understand for non-devs by separation, and devs who know while)
