### ISSUE TITLE
Ability to Inject javascript or html

### ISSUE THREAD

**Issue by lorico** [MontFerret/ferret#264]
Hi, I really love FQL this is totally amazing work!!!

I was wondering if there is any wayto inject HTML code or JAVASCRIPT code into a document ?
A function like: 
`SET('body', '<H1>HELLO</H1>')`
or
`SET('body', 'document.getElementById("demo").innerHTML = "Hello JavaScript!";')`

Sorry if I missed it.. thanks !

**Comment by ziflex** [comment]
@lorico hey, thank you for your kind words, I'm glad that you like it!

At this moment, we are not planning to let users execute arbitrary JS code from their queries, but, DIM manipulations are on the list. 
Let me create an issue for that, so you could track the progress.

**Comment by lorico** [comment]
perfect, thanks a lot !
