### ISSUE TITLE
Split CLI and runtime packages

### ISSUE THREAD

**Issue by ziflex** [MontFerret/ferret#266]
As the project grows, it's getting more messy to keep everything in one place.

The proposal is to split the project into following separate repos:

- [ ] ``ferret`` will contain only Ferret itself - parser, compiler, runtime and stdlib
- [x] ``cli`` will contain CLI.

Any thoughts?

**Comment by PierreBrisorgueil** [comment]
hey, if that doesn't complicate the installation for users / workers that might be a good idea. 

if the feeling of complication by the size occurs, it’s necessary. You just have to add the explication to the readme for easy pull requests 🤔
