### ISSUE TITLE
failed to initialize driver: malformed ws or wss URL

### ISSUE THREAD

**Issue by advancedlogic** [MontFerret/ferret#272]
Opening chrome in remote debug mode ( 

> google-chrome --remote-debugging-port=9222 --user-data-dir=./ 

) and starting Ferret REPL (or using Ferret in Embedded mode) I get this error:

`"error":"failed to initialize driver: malformed ws or wss URL","driver":"cdp","message":"failed to initialize the driver"`

**Comment by 3timeslazy** [comment]
Send script, please

**Comment by advancedlogic** [comment]
your demo script:

```
LET google = DOCUMENT("https://www.google.com/", true)

INPUT(google, 'input[name="q"]', "ferret", 25)
CLICK(google, 'input[name="btnK"]')

WAIT_NAVIGATION(google)

FOR result IN ELEMENTS(google, '.g')
    // filter out extra elements like videos and 'People also ask'
    FILTER TRIM(result.attributes.class) == 'g'
    RETURN {
        title: INNER_TEXT(result, 'h3'),
        description: INNER_TEXT(result, '.st'),
        url: INNER_TEXT(result, 'cite')
    }

Google chrome version:  61.0.3163.100
```

**Comment by ziflex** [comment]
@advancedlogic I've tried with the version and it seems CDP does not support it. 
I can just recommend either to update your Chrome or use Docker container with Chrome 7x version.
