### ISSUE TITLE
Docker scratch image problem

### ISSUE THREAD

**Issue by zmajew** [MontFerret/ferret#277]
First, thanks for Ferret!
I will use your 'Embedded mode' example to explain my problem.
When I make docker image from ferret example it works fine, but when I make a FROM scratch image the script times out waiting to load the page. Here are Dockerfiles:

This one work fine:
`
FROM golang

ENV GO111MODULE=on

WORKDIR /app

COPY go.mod .

COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o ferret .

ENTRYPOINT ["/app/ferret"]`

This one works but does not load the page (timed out):
`FROM golang AS builder

ENV GO111MODULE=on

WORKDIR /app

COPY go.mod .

COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o ferret .

FROM scratch

COPY --from=builder /app/ferret /app/

ENTRYPOINT ["/app/ferret"]
`
What I am missing? 
Thanks

**Comment by 3timeslazy** [comment]
@zmajew it should works
```docker
FROM golang AS builder

ENV GO111MODULE=on

WORKDIR /app

COPY go.mod .

COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOARCH=amd64 go build -o ferret .

FROM scratch

COPY --from=builder /app/ferret /app/

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ENTRYPOINT ["/app/ferret"]
```

more about deploying on scratch images [here](https://weberc2.bitbucket.io/posts/golang-docker-scratch-app.html)
