### ISSUE TITLE
param: unexpected end of JSON input

### ISSUE THREAD

**Issue by akornatskyy** [MontFerret/ferret#279]
The command line parameter "--param" does not support colon.

**To Reproduce**
```sh
$ ferret.exe --param=url:\"http://example.com\" test.fql
```

**Expected behavior**
Colon (":") is supported as param.

**Fix**
When params is [converted to map](https://github.com/MontFerret/ferret/blob/master/main.go#L32) it uses strings.Split, which slices a string into all substrings separated by ":".

```go
pair := strings.Split(entry, ":")
```

instead it should be limited to just 2.
```go
pair := strings.SplitN(entry, ":", 2)
```

use [strings.SplitN](https://golang.org/pkg/strings/#SplitN) instead.

**Comment by 3timeslazy** [comment]
@akornatskyy good catch!  Would you like to do PR that fix it? Or we can do it ourselves.

**Comment by akornatskyy** [comment]
please fix.
