### ISSUE TITLE
Fix arithmetic operators

### ISSUE THREAD

**Issue by ziflex** [MontFerret/ferret#295]
The arithmetic operators must accept operands of any type. Passing non-numeric values to an arithmetic operator must cast the operands to numbers:

- ``NONE`` will be converted to ``0``
- ``false`` will be converted to ``0``, ``true`` will be converted to ``1``
- a valid numeric value remains unchanged, but ``NaN`` and Infinity will be converted to ``0``
- string values are converted to a number if they contain a valid string representation of a number. Any whitespace at the start or the end of the string is ignored. Strings with any other contents are converted to the number ``0``
- an empty array is converted to ``0``, an array with one member is converted to the numeric representation of its sole member. Arrays with more members are converted to the number ``0``.
- objects, binary and custom types are converted to the number ``0``.

Here are a few examples:

Upd:
```javascript
1 + "a"                 // "1a"
1 + "99"                // "199"
1 + NONE                // 1
NONE + 1                // 1
3 + [ ]                 // 3
24 + [ 2 ]              // 26
24 + [ 2, 4 ]           // 30
25 - NONE               // 25
17 - true               // 16
23 * { }                // 0
5 * [ 7 ]               // 35
5 * [ 7, 2 ]               // 45
24 / "12"               // 2
1 / 0                   // panic
```

**Comment by 3timeslazy** [comment]
What about converting array to sum of the array's members? 
```
0 + [] == 0
0 + [1] == 1
0 + [1, 2] == 3
```
I think, looks good. This condition includes all of the above.

**Comment by 3timeslazy** [comment]
Also, I do not like that `1 / 0 == 0`
I suggest 2 options:
* `1 / 0 == panic`
* `1 / 0 == Inf`, but we need to add `Inf` this way.

**Comment by ziflex** [comment]
```1 / 0 == panic``` this is the current behavior.

**Comment by 3timeslazy** [comment]
And this is good behavior.

**Comment by 3timeslazy** [comment]
One more question. What is the value of the expression `1 + "11a"`?

**Comment by ziflex** [comment]
According to Arango, it would be 1, since "11a" won't be possible to convert into an integer.
But, I think I will change the requirements for this. I would prefer a string as a result. (In AQL, you can't use ``+`` operator for string concatenation).

**Comment by ziflex** [comment]
@3timeslazy what do you think about this: ```24 / "12"               // 2```

**Comment by 3timeslazy** [comment]
@ziflex I think it OK

**Comment by ziflex** [comment]
What about dates?

**Comment by ziflex** [comment]
Arrays?

```
[1] + [1]
```
```
[1,2] + [1]
```
```
[1,2] + [3,4]
```

**Comment by 3timeslazy** [comment]
@ziflex  
```
[1, 1]
```
```
[1, 2, 1]
```
```
[1, 2, 3, 4]
```

**Comment by ziflex** [comment]
> @ziflex
> 
> ```
> [1, 1]
> ```
> 
> ```
> [1, 2, 1]
> ```
> 
> ```
> [1, 2, 3, 4]
> ```

What about subtractions, multiplications and divisions?
