### ISSUE TITLE
Share your use case

### ISSUE THREAD

**Issue by ziflex** [MontFerret/ferret#302]
Hello folks!

I would like to ask you to share your use cases of using Ferret in order to better understand in which direction the project should move.

**Comment by kaixinbuyu** [comment]
I'm using Ferret heavily for more than one year on my commercial AI-powered crawler product(lunch soon) which has the following benefits:

**1.auto extract list tables from list page;**
   ----auto extract tables from single list html by machine learning;
**2.auto extract detail fields and tables from detail page;**
   ----auto extract tables from multi detail html by machine learning;
**3.support ajax pages**
   -----using Ferret to download ajax pages!
**4.support custom logic like URL generating,etc**
   ------using Ferret as a DSL language to extract and generate urls,parameters.(still working on it...)
5.other normal crawler functions like distributed,support cookie pool,proxy-ip;
   ------using golang,rpc

By using this AI crawler,**Anyone can crawl most web pages into Excel tables in One minute!**
**Anyone can create 1000 crawler in a day.**
And much faster than import.io and diffbot.
Lunch soon!

**Comment by ziflex** [comment]
Thanks for sharing!
Is there something you would want to add to Ferret in the future?

**Comment by kaixinbuyu** [comment]
I spent few time on web download layer,in most case ferret is sufficient,
most time is spent on automatic web extract layer(It is difficult and worked for almost 3 years). 

I created 2 DSL,one for downloding(99% in ferret,downloading ajax pages,browser automation),
and the other one for extracting logic(working in process) for better paralleling and implementing.

In the future,If anyone is interesting on add a web GUI like a following SQL editor(which is mostly in draft),I'd like to contribute to archive this:

**insert into "d:/abc.xls"
 --or create table tb_xxx as    -- storage layer
select        --pipeline layer
 ".title","img#icon1",".text",substring(".content",0,100),  --1.basic ferret element selector
extract_email(".span1") as email,replace(".text","a","b"),  --2.data preprocess udf
key_words(".content") as key_words,Sentiment_analysis(".p.comment")  --3.machine learning,NLP
from "www.abc.com/page/[1:100]"'
where driver = 'cdp'     --download layer
-- or driver = 'http' and  threads = 5    --schdule layer
and cookie = "k1=v1;k2=v2"
and after_page_load = "input('search_text','iphone');click('btn_search')"** 

and the data grid result is showed(and beautiful chat,dashboard)

**Comment by ziflex** [comment]
Speaking of GUI, there is [Dashboard UI](https://github.com/MontFerret/ferret-server-ui) for [Ferret Server](https://github.com/MontFerret/ferret-server), it's still WIP, but you are welcome to contribute.

**Comment by ap0** [comment]
We are using it to scrape home showing data for our company’s real estate listings because they provide no API to access it. Overall it’s been a pretty solid solution save for issues where the sites we scrape are slow to load or have issues due to lots of SSO redirection. A nice to have feature would be something like “navigate to a URL and wait for it to get to this other URL after a series of redirections”

**Comment by ziflex** [comment]
@ap0 thank you for sharing!
Hmm, this is definitely something we need to think about. Thanks for the idea!

**Comment by ziflex** [comment]
@ap0 how did you integrate it? Are you using it via script as a CLI or embedded into your scraping system?

**Comment by kaixinbuyu** [comment]
I have another interesting idea,and there are some people working on it:
eg,how to crawl 1~1000+ sub-page's comments in product-detail page?

```
open url
for 1..visible('a.next-page')
      click('a.next-page') 
      save_ajax_response_parsed_html()
```

 this script triggers ajax requests for 50+ times(.)

```
http://www.abc.com?get_product_comments?product_id=10001&page_id=1&page_num=20&...
http://www.abc.com?get_product_comments?product_id=10001&page_id=2&page_num=20&...
http://www.abc.com?get_product_comments?product_id=10001&page_id=3&page_num=20&...
...
http://www.abc.com?get_product_comments?product_id=10001&page_id=50&page_num=20&...
```
 
and browser render ajax response 50+ times ... it is of course slow....

how about intercept the first 1~10 ajax requests,then use machine learning to auto detect the following requests should be:
```
page_id=1&page_num=100
page_id=2&page_num=100
page_id=3&page_num=100
page_id=4&page_num=100
page_id=5&page_num=100
```
and convert all chrome requests to HTTP request in background.

in a word,bring headless chrome some intelligent fetures.

**Comment by ap0** [comment]
> @ap0 how did you integrate it? Are you using it via script as a CLI or embedded into your scraping system?

We embed it into the scraping system.

**Comment by hubitor** [comment]
I would like to extract data from a each row of a given listing. Extract the links if they exist in the rows, follow these links, extract content form these pages. This must be done for all pages of the listing.

I personally would be very happy for any direction that would make scraping fast and mostly automatized.

**Comment by suntong** [comment]
Structured scrapping, 

The following is the approach that I had been needing the most (adapted from https://github.com/andrew-d/goscrape):

The architecture of scraping is roughly as follows:

- A single request to start scraping (from a given URL).
- Each scrape consists of some number of *pages*.
- Inside each page, there's 1 or more *blocks* - some logical method of splitting
  up a page into subcomponents.  By default, there's a single block that consists
	of the pages's `<body>` element, but you can change this fairly easily.
- Inside each block, you define some number of *pieces* of data that you wish
  to extract.  Each piece consists of a name, a selector, and what data to
	extract from the current block.

Almost every single task that I need to do falls within such description. 

Like in https://www.montferret.dev/cookbook/google-search/, but need an outer loop to walk page by page until limit is reached.
