### ISSUE TITLE
left square bracket does not work

### ISSUE THREAD

**Issue by Sangokan34** [MontFerret/ferret#303]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Sangokan34** [comment]
Welcome to Ferret REPL 0.7.0
Please use `exit` or `Ctrl-D` to exit this program.
[ hopeless??

**Comment by ziflex** [comment]
@Sangokan34 hi, thanks for giving Ferret a try!

It's an expected behavior, since Ferret REPL by default expects to receive full query in one line which should ends with RETURN or FOR IN statements.
If you want to switch to multi line mode, start and your query with ``%`` character.

```sh
Welcome to Ferret REPL 0.7.0
Please use `Ctrl-D` to exit this program.
>%
>LET doc = DOCUMENT('https://news.ycombinator.com/')
>FOR post IN ELEMENTS(doc, '.storylink')
>RETURN post.attributes.href
>%
```
