### ISSUE TITLE
How to get http status code?

### ISSUE THREAD

**Issue by megabait1212** [MontFerret/ferret#305]
HI,
How to get HTTP status code?
Could you advise how to identify HTTP errors, for example, page not found or access was forbidden and so on? Thank you

**Comment by ziflex** [comment]
Hi @megabait1212 !

At this moment, there is no way to get this data. 
But this is a good idea to provide more context to an error.

**Comment by ziflex** [comment]
The question is, what should we do if we receive a code other than 200? 
Should we return an error?
@davad @3timeslazy

**Comment by davad** [comment]
I don't think so. A non-200 code isn't necessarily an 'error' as far as a Ferret user is concerned. E.g. maybe you're interested in scraping fun looking 404 error pages XD

**Comment by ziflex** [comment]
Probably, we need to add a new property to ``HTMLPage`` object called ``response`` or something like this. The object would contain some information like response code, headers and etc.

**Comment by asitemade4u** [comment]
I think it is essential to be able to detect a 404. Some web developers are sloppy and leave a lot of stale links in their pages...

**Comment by ziflex** [comment]
Ability to get status was added. Feel free to reopen if you still have issues with it.
