### ISSUE TITLE
WAIT_ELEMENT

### ISSUE THREAD

**Issue by heiheshang** [MontFerret/ferret#307]
I'm trying to use this function in an embedded solution, but I get an error
`2019/06/10 21:02:34 not supported: WAIT_ELEMENT(doc,'#TPL_username_1',5000) at 3:16`
what am I doing wrong ?

**Comment by ziflex** [comment]
Hi @heiheshang !

I assume you are using a wrong HTML driver.
Could you show me how you register a driver you are using?
There are 2 types HTML drivers at this moment - CDP and HTTP.

HTTP driver is a static driver, that just downloads an html page and parses it in memory. It does not support user interactions.

On the other side, there is CDP (Chrome DevTools Protocol) which uses Chrome to load HTML pages and this drivers supports user interactions. This is the driver you need.

[Here is an example how to set it up](https://github.com/MontFerret/ferret/blob/master/cli/options.go#L32).

**Comment by heiheshang** [comment]
really wrong driver
