### ISSUE TITLE
DOCUMENT the third parameter is ambiguous 

### ISSUE THREAD

**Issue by lukeyMing** [MontFerret/ferret#308]
**Describe the bug**

DOCUMENT the third parameter is ambiguous.

version:  github.com/MontFerret/ferret v0.7.0
code : github.com/MontFerret/ferret/pkg/stdlib/html/document.go
line : 108

`res.Timeout = time.Duration(timeout.(values.Int)) + time.Millisecond`

should replace + to * ??

**Desktop (please complete the following information):**
 - OS: [win10]
 - Browser [chrome]
 - Version [75.0.3770.80]

**Comment by ziflex** [comment]
It definitely should!
Good catch! :)

**Comment by ziflex** [comment]
[Fixed](https://github.com/MontFerret/ferret/blob/master/pkg/stdlib/html/document.go#L108)
