### ISSUE TITLE
screenshot ?

### ISSUE THREAD

**Issue by heiheshang** [MontFerret/ferret#309]
tell me how to take a screenshot, I do not see examples

**Comment by ziflex** [comment]
Hey @heiheshang,

you can use ```SCREENSHOT``` function for that.
It accepts both url and open CDP doc object.

```
Welcome to Ferret REPL 0.7.0
Please use `exit` or `Ctrl-D` to exit this program.
> %
> LET doc = DOCUMENT("https://github.com/MontFerret/ferret/issues/309", { driver: "cdp" })
> RETURN { data: SCREENSHOT(doc) }
> %
```
or

```
Welcome to Ferret REPL 0.7.0
Please use `exit` or `Ctrl-D` to exit this program.
> %
> RETURN { data: SCREENSHOT("https://github.com/MontFerret/ferret/issues/309") }
> %
```

There is a caveat though. 
At this moment, Ferret output is JSON. Which means, all binary data gets transformed into base64 string.
If you do not want it, you can create a wrapper (embedder) around Ferret and register a function that would save output to a file system. 

Currently, there are not FS related functions in Ferret.

**Comment by heiheshang** [comment]
How to set the image size and format?

**Comment by ziflex** [comment]
‘’’go
// Screenshot takes a screenshot of the current page.
// @param source (Document) - Document.
// @param params (Object) - Optional, An object containing the following properties :
// 		x (Float|Int) - Optional, X position of the viewport.
// 		x (Float|Int) - Optional,Y position of the viewport.
// 		width (Float|Int) - Optional, Width of the viewport.
// 		height (Float|Int) - Optional, Height of the viewport.
// 		format (String) - Optional, Either "jpeg" or "png".
// 		quality (Int) - Optional, Quality, in [0, 100], only for jpeg format.
// @returns data (Binary) - Returns a base64 encoded string in binary format.
‘’’

**Comment by heiheshang** [comment]
I don't understand how to write it down

**Comment by heiheshang** [comment]
The screenshot returns a string with no content type, it would be convenient if at the beginning of the string there was a data file type: image / jpeg; base64, now I have to fix the file type

**Comment by ziflex** [comment]
> The screenshot returns a string with no content type, it would be convenient if at the beginning of the string there was a data file type: image / jpeg; base64, now I have to fix the file type

You can return it as an object and add all required information manually:

```
LET data = SCREENSHOT("https://github.com/MontFerret/ferret/raw/master/assets/logo.png")
RETURN { type: "png", data }
```

**Comment by heiheshang** [comment]
`reader := base64.NewDecoder(base64.StdEncoding, strings.NewReader(res.Res))
 m, formatimage, err := image.Decode(reader)`
if so, then the extra field is superfluous

**Comment by ziflex** [comment]
Try this:

```go
package main

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"image"
	"os"

	"github.com/MontFerret/ferret/pkg/compiler"
	"github.com/MontFerret/ferret/pkg/drivers"
	"github.com/MontFerret/ferret/pkg/drivers/cdp"
	"github.com/MontFerret/ferret/pkg/drivers/http"
)

type Image struct {
	Type    string `json:"type"`
	Content string `json:"content"`
}

func main() {
	img, err := getImage()

	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	content, _ := base64.StdEncoding.DecodeString(string(img.content))

	switch img.Type {
	case "png":
		pngI, err = png.Decode(content)
		// ...
	case "jpeg":
		jpgI, err = jpeg.Decode(content)
		// ...
	}
}

func getImage() (*Image, error) {
	query := `
		LET data = SCREENSHOT("https://github.com/MontFerret/ferret/raw/master/assets/logo.png")
RETURN { type: "png", content: data }
	`

	comp := compiler.New()

	program, err := comp.Compile(query)

	if err != nil {
		return nil, err
	}

	ctx := context.Background()
	ctx = drivers.WithContext(ctx, cdp.NewDriver(), drivers.AsDefault())

	out, err := program.Run(ctx)

	if err != nil {
		return nil, err
	}

	res := &Image{}

	err = json.Unmarshal(out, &res)

	if err != nil {
		return nil, err
	}

	return res, nil
}
```

**Comment by simonkuang** [comment]
> Hey @heiheshang,
> 
> you can use `SCREENSHOT` function for that.
> It accepts both url and open CDP doc object.
> 
> ```
> Welcome to Ferret REPL 0.7.0
> Please use `exit` or `Ctrl-D` to exit this program.
> > %
> > LET doc = DOCUMENT("https://github.com/MontFerret/ferret/issues/309", { driver: "cdp" })
> > RETURN { data: SCREENSHOT(doc) }
> > %
> ```
> 
> or
> 
> ```
> Welcome to Ferret REPL 0.7.0
> Please use `exit` or `Ctrl-D` to exit this program.
> > %
> > RETURN { data: SCREENSHOT("https://github.com/MontFerret/ferret/issues/309") }
> > %
> ```
> 
> There is a caveat though.
> At this moment, Ferret output is JSON. Which means, all binary data gets transformed into base64 string.
> If you do not want it, you can create a wrapper (embedder) around Ferret and register a function that would save output to a file system.
> 
> Currently, there are not FS related functions in Ferret.

I got a error message following the above command.

> Failed to execute the query
invalid type: expected HTMLDocument or string, but got HTMLPageType: SCREENSHOT(doc) at 18:15: RETURN{data:SCREENSHOT(doc)} at 18:0

**Comment by ziflex** [comment]
@simonkuang could you create a separate issue for this?
It's related to recent refactoring.

**Comment by PierreBrisorgueil** [comment]
@ziflex I encountered the error today without finding @simonkuang issue@ziflex

so : https://github.com/MontFerret/ferret/issues/542
