### ISSUE TITLE
ATTR_GET not found

### ISSUE THREAD

**Issue by advancedlogic** [MontFerret/ferret#310]
I am trying to get the attribute "title" of a SPAN:

`<span class="aClass" title="aString">Some text</span>`

with

`LET object = ATTR_GET(el, "title")`

but got ATTR_GET not found.

**Comment by ziflex** [comment]
Hi @advancedlogic,
What version of Ferret are you using?
I have just tried to use the functions and it's there.

```bash
Welcome to Ferret REPL 0.7.0
Please use `exit` or `Ctrl-D` to exit this program.
> %
> LET doc = DOCUMENT('https://github.com/MontFerret/ferret/issues/310')
> RETURN ATTR_GET(ELEMENT(doc, "body"), 'class')
> %
{"class":"logged-out env-production min-width-lg"}
```

**Comment by advancedlogic** [comment]
My bad ... version 0.6.0
I apologize
