### ISSUE TITLE
SendKeys ?

### ISSUE THREAD

**Issue by heiheshang** [MontFerret/ferret#311]
I do not see the SendKeys method, is it possible to add it?

**Comment by ziflex** [comment]
Hey, what is SendKeys method?

**Comment by jbpratt78** [comment]
Are you trying to simulate a key press event programmatically?

**Comment by heiheshang** [comment]
Yes, you need to send a value in the input field, if you just assign it, the site will know that I am a robot

**Comment by ziflex** [comment]
Use INPUT function

**Comment by heiheshang** [comment]
I just use it. Before that, I used another driver, when you fill in via SendKeys, problems do not arise, if you set the value to input, the site disassociates me as a robot

**Comment by ziflex** [comment]
It does not set a value. It sends keys with different delays that emulates user’s behavior.

**Comment by heiheshang** [comment]
[https://yadi.sk/i/4hVA9TDylhlLFQ](url)
then it is not clear why this happens. The window size is incorrectly determined by the site, scrollbars appear, how can I set the size of the browser window?
