### ISSUE TITLE
How to specify user-agent in .fql?

### ISSUE THREAD

**Issue by leopku** [MontFerret/ferret#317]
```
let doc = DOCUMENT('http://httpbin.org/anything', {
  userAgent: 'xxx'
})
```

above code seems not effected.
What's the right way?

**Comment by ziflex** [comment]
Good catch!
It should work, but by some reason, the code is not there :)

**Comment by ziflex** [comment]
You can still do this using ``cdp`` driver, but you will need Chrome for it.

``
LET doc = DOCUMENT('http://httpbin.org/anything', {
  driver: 'cdp',
  userAgent: 'xxx'
})
```

**Comment by leopku** [comment]
Sorry for lately reply.
It works now.
Thanks a lot.
