### ISSUE TITLE
WAIT_NAVIGATION timeout error ,the newest master version

### ISSUE THREAD

**Issue by kaixinbuyu** [MontFerret/ferret#332]
update to the newest master version
run the embeded script in example directory:
github.com/MontFerret/ferret/examples/embedded.go

```
query := `
		LET doc = DOCUMENT("https://www.baidu.com",true) //any link
		WAIT_NAVIGATION(doc,30000)
		RETURN doc.url
	`
```

the error info is:
`operation timed out: WAIT_NAVIGATION(doc,30000) at 3:2`

I debuged the code and found that :

1.the EventLoad is registed at 2 place ok(page's NewHTMLPage,page's WaitForNavigation)
2.the page load event(EventLoad) is triggered(broker's emit) ok,(by close ch)
3.the page 's NewHTMLPage received the load event ok.
4.but the page's WaitForNavigation does not received this event???

```
func (p *HTMLPage) WaitForNavigation(ctx context.Context) error {
	onEvent := make(chan struct{})
	var once sync.Once
	listener := func(_ context.Context, _ interface{}) {
		once.Do(func() {
			close(onEvent)
		})
	}

	defer p.events.RemoveEventListener(events.EventLoad, listener)

	p.events.AddEventListener(events.EventLoad, listener)  **//<--not received the load event**

	select {
	case <-onEvent:
		return nil
	case <-ctx.Done():
		return core.ErrTimeout
	}
}
```

**Comment by ziflex** [comment]
Hey, thanks for looking into it. I will try to fix it this weekend.

**Comment by ziflex** [comment]
Btw, you don't really need to use ``WAIT_NAVIGATION`` function when you are loading a document.
It's already handled by ``DOCUMENT``.

**Comment by kaixinbuyu** [comment]
Thanks for your suggest.I'll try it again.
so,WAIT_NAVIGATION is mostly used for "next-page-link" click?

**Comment by ziflex** [comment]
> 1,so,WAIT_NAVIGATION is mostly used for "next-page-link" click?

Yes, this function should be used when Ferret does not know that there is a navigation going on.

>2.I tried a sample script to test the timeout error again.
> github.com/MontFerret/ferret/examples/embedded.go

>```
> query := `
>		LET doc = DOCUMENT("about:blank",true)
>		WAIT(1000)
>
>		NAVIGATE(doc, "https://www.baidu.com/",30000)
>		WAIT(1000)
>		RETURN doc.url
>	`
>```
>(1)there is no error with the old ferret version(0.7.0)
>(2)there is the same timeout error with the newest master version:
>operation timed out: NAVIGATE()
>
>So there must be something wrong with the new version's Document or Page Object.

I'm looking into that. Thanks for reporting the bug!

**Comment by PierreBrisorgueil** [comment]
@ziflex i confirm the bug, maybe some informations, this happens to me only when chrome is launched in headless. I will try with an old version.

**Comment by ziflex** [comment]
@PierreBrisorgueil thanks!
I found the root cause - deadlock :( I will ship a fix soon.

**Comment by PierreBrisorgueil** [comment]
@ziflex ok, thx ! I will work with a simpler query in the meantime, do not hesitate to contact me by mail if you need an example of a complex query to test.

I'm surprised that mine works when chrome is not launched in headless mode O.O

**Comment by ziflex** [comment]
@kaixinbuyu, @PierreBrisorgueil guys, can you verify the fix?

**Comment by PierreBrisorgueil** [comment]
@ziflex hello, I'm not sure how to do it, what I have done : 

- [x] go in src/github.com/MontFerret/ferret
- [x] pull ugfix/#332-nav-deadlock
- [x] force rebuild based on new branch ? `go install -a github.com/MontFerret/ferret `

result : 

```
Failed to execute the query
operation timed out: WAIT_NAVIGATION(doc)
``` 

always, only in headless mode, it may be related to my specific case. The page includes a loader when passing from one to the other, before loading a list, so I use  :  

```
WAIT_NAVIGATION(doc)
WAIT_ELEMENT(doc, '.search-travel-results', 10000)
```
I can send my requests by email if needed.

I have no problem with this simple example, but not either before your PR 

```
LET doc = DOCUMENT("https://weareopensource.me", true)
CLICK(".nav-hobbies")
WAIT_NAVIGATION(doc)
WAIT_ELEMENT(doc, '.post-feed')
FOR el IN ELEMENTS(doc, '.post-card-title')
    RETURN TRIM(el.innerText) 
```

**Comment by ziflex** [comment]
You can join [our Discord channel](https://discord.gg/kzet32U) and write a message to me.

**Comment by ziflex** [comment]
I'm gonna merge the PR and continue testing.

**Comment by kaixinbuyu** [comment]
NAVIGATION works now.
I will do more test on it.
