### ISSUE TITLE
Running ferret on ECS

### ISSUE THREAD

**Issue by rhlr** [MontFerret/ferret#339]
I'm running the `chrome-headless-stable` docker on ECS and using the public IP address as the `--cdp` . Now when I try to to run the following example, it either exceed the timeout or gives the response in almost 23-25 seconds.

LET google = DOCUMENT("https://www.google.com/", true)
INPUT(google, 'input[name="q"]', "ferret", 25)
CLICK(google, 'input[name="btnK"]')

WAIT_NAVIGATION(google)

FOR result IN ELEMENTS(google, '.g')
    // filter out extra elements like videos and 'People also ask'
    FILTER TRIM(result.attributes.class) == 'g'
    RETURN {
        title: INNER_TEXT(result, 'h3'),
        description: INNER_TEXT(result, '.st'),
        url: INNER_TEXT(result, 'cite')
    }

Has anyone tried running it on ECS before ?
P.S.- It runs properly if I run both the `chrome-headless` browser and the ferret instance on the same server.

**Comment by ap0** [comment]
The way I run it is to have an ECS task definition with two containers, one for `chrome-headless` and one for my app.  I can connect to the headless Chrome instance via `http://localhost:9222` and have never encountered any latency issues.  I haven't tried to do it over the network, though.

What instance size are you using?  I found the performance to be unacceptable on anything less than a 4-core machine.

**Comment by rhlr** [comment]
8GB RAM, 4 vCPU. Can you tell me the settings of ECS you provide while running the `chrome-headless` including the volume to mount.
