### ISSUE TITLE
TravisCI is broken

### ISSUE THREAD

**Issue by ziflex** [MontFerret/ferret#344]
Unable to install ``oracle-java9-set-default`` package.

```bash
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install oracle-java9-set-default
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package oracle-java9-set-default
```

**Comment by u5surf** [comment]
Hi, 
Oracle JDK seems to have moved  the archive.
How about trying to replace openjdk? it’s suitable to alter one
https://github.com/Lastimoso/rubygems.org/commit/d839248a19e95a717a7d7dcfdf25e8a99e9516b7
