### ISSUE TITLE
How to change value of a variable

### ISSUE THREAD

**Issue by vartika102** [MontFerret/ferret#350]
I want to use a variable as a counter variable whose value needs to be changed when a particular condition is satisfied. I initialized a variable as "LET counter = 0", and when I tried to change it as follows "counter = 1", it gives an error. How to solve it? Thank you in advance.

**Comment by ziflex** [comment]
Hi @vartika102 !
Variables in FQL are immutable, once set, there is not way to reassign them.

Are you using Ferret as a CLI or a library?
In case as a library, you can workaround it by registering a custom function that mutates an object.

**Comment by vartika102** [comment]
I'm using Ferret as CLI and not library.

**Comment by ziflex** [comment]
@vartika102 could you give me an example of wha you are trying to achieve?

**Comment by vartika102** [comment]
Well, I wanted to use a variable as a counter in a loop and increment it up to a certain value after which I could stop the loop from running. This issue was a part of a bigger problem but I found out another way of solving with the release of the recent version of Ferret. Thanks for the help.
