### ISSUE TITLE
How can i get full page source?

### ISSUE THREAD

**Issue by dulumao** [MontFerret/ferret#369]
How can i get full page source?

**Comment by ziflex** [comment]
@dulumao hey!

You have several options:
- if you just need a page source and the target page is static (nothing rendered by JS), you can use the following example:

```
LET p = DOWNLOAD("https://github.com/MontFerret/ferret/issues/369")
RETURN TO_STRING(p)
```
- if the page you need to get the source from is dynamic (content is rendered by JS), you need to use ``DOCUMENT`` function and have running Chrome/Chromium with open debugging port.
Here is an example of the query:

```
LET p = DOCUMENT("https://github.com/MontFerret/ferret/issues/369", { driver: 'cdp' })
RETURN p.innerHTML
```

**Comment by dulumao** [comment]
@ziflex lol,thx
