### ISSUE TITLE
Fix browser launcher

### ISSUE THREAD

**Issue by ziflex** [MontFerret/ferret#38]
If CLI is started with ```--cdp-launch``` flag, it should check whether Chrome is running and if not, open a new instance with ```--remote-debugging-port``` flag.

- [x] macOS
- [x] Linux
- [x] Windows

**Comment by gedw99** [comment]
For OSX this works for me from Make file:

````
open -a "Google Chrome Canary" --args -remote-debugging-port=9222 -user-data-dir=$(PWD)/_chrome
````

I am using Chrome canary
I also set a new user data dir, so its not using my other user accounts within chrome. 

Wrapping this in a golang cmd should work..

**Comment by ziflex** [comment]
@gedw99 it should work, but, by some reason, I could not make it work.

**Comment by gedw99** [comment]
Any more info then to try to work out why it's not working ?
Is chrome canary installed ?

**Comment by ziflex** [comment]
@gedw99 hey, I have tried to launch it again (not Canary version).
And here is what I got:

```sh
fork/exec open -a /Applications/Google Chrome.app --args: no such file or directory
```

**Comment by ziflex** [comment]
Fixed in [new CLI](https://github.com/MontFerret/cli).
