### ISSUE TITLE
Offline stream

### ISSUE THREAD

**Issue by bundleman** [MontFerret/ferret#383]
I am writing a caching scraper.
And I want to use an offline (from []byte) stream for scraping  I did not find such an opportunity in ferret.

**Comment by ziflex** [comment]
Hey @bundleman.
Not quite sure that I understand you. Do you mean loading pre-saved html files into Ferret runtime?

**Comment by bundleman** [comment]
@ziflex that can be closed , because you created this -> https://github.com/MontFerret/ferret/issues/385. Thanks.
