### ISSUE TITLE
Load HTML pages from memory

### ISSUE THREAD

**Issue by ziflex** [MontFerret/ferret#385]
Ferret used to have this feature but during one of the refactorings it was decided to remove it.

Let's bring it back.

- Add ``Parse(ctx context.Context, content []byte) (HTMLPage, error)`` method to ``Driver`` interface.

- Use [this method](https://chromedevtools.github.io/devtools-protocol/tot/Page#method-setDocumentContent) in CDP driver.

- Use ``goquery.NewDocumentFromReader`` in HTTP driver.

- Add ``HTML_PARSE`` function to ``html`` library.

**Comment by clock21am** [comment]
hey @ziflex  could you please explain this issue a bit more in detail?

**Comment by ziflex** [comment]
@clock21am sure!

In Ferret, we have a concept of HTTP drivers that represent different implementations of access to HTML pages.
[Here](https://github.com/MontFerret/ferret/blob/master/pkg/drivers/driver.go) is an interface: 
```go
type Driver interface {
    io.Closer
    Name() string
    Open(ctx context.Context, params Params) (HTMLPage, error)
}
```

Currently, we have 2 drivers:

- Static driver, that retrieves pages by a regular HTTP call and stores them in memory.
- Dynamic driver, that uses CDP (Chrome Devtools Protocol) to control Chrome/Chromium remotely and provides an access to DOM through it.

And for now, there is only one way how to load a page - you should call a hosting server i.e. make a request. 
In case of a static driver, we just make an HTTP GET request to a given url. 
In case of dynamic one, we open a tab in a browser and navigate it to a target url.

All that happens when you call ``driver.Open`` method.
In both scenarios, the webpage must be hosted.

What this task for is to add an ability to load a pre-fetched HTML file into a one of the above drivers.

The idea of how it should be implemented is in the description.

**Comment by clock21am** [comment]
Hey @ziflex thanks alot for the deep description, Let me take a look.

**Comment by laylwintthu396** [comment]
I Love Children.

**Comment by patrikhl** [comment]
Any progress on this? Otherwise I will take a look at it.

**Comment by clock21am** [comment]
Hey so sorry, was occupied with the office stuffs the last week, will take a look on it this weekend. if you fix it before go ahead.
