### ISSUE TITLE
failed to initialize driver: could not resolve IP for 0.0.0.0: DOCUMENT('https://www.amazon.com/',true) at 1:13

### ISSUE THREAD

**Issue by ElToro13** [MontFerret/ferret#389]
I am trying to run pagination.fql and it keeps giving me this error. I dont know where the issue is coming from.

**Comment by ziflex** [comment]
Hey, thanks for giving Ferret a try!

Do you have a running Chrome instance with open debugging port locally?

**Comment by ElToro13** [comment]
It keep saying chrome not found..I keep the exe file in the same directory..

**Comment by ziflex** [comment]
Ferret does not launch Chrome by default. Use ``--cdp-launch=true`` for that or launch it manually with open debugging port: ``chrome.exe --remote-debugging-port=9222``
