### ISSUE TITLE
Add IO functions

### ISSUE THREAD

**Issue by ziflex** [MontFerret/ferret#395]
Let's add functions that implement IO operations.

We need to cover 2 areas for now:

- File system
- Network (HTTP)

Each of the areas must be in a dedicated namespace:

- ``IO::FS::READ(path: string)``, ``IO::FS::WRITE(path: string, data: []bytes)``
- ``IO::NET::HTTP::GET(url: string, params?: object)``, ``IO::NET::HTTP::POST(params: object)``, ``IO::NET::HTTP::PUT(params: object)``, ``IO::NET::HTTP::DELETE(url: string, params?: object)``

Did I miss something?

More detailed API will be discussed later.

Here is a list of things we need to add for starters:
- [x] IO::FS::READ
- [x] IO::FS::WRITE
- [ ] IO::FS::DELETE (do we need it?)
- [ ] IO::NET::HTTP::GET
- [ ] IO::NET::HTTP::POST
- [ ] IO::NET::HTTP::PUT
- [ ] IO::NET::HTTP::DELETE

**Comment by 3timeslazy** [comment]
Can take this

**Comment by ziflex** [comment]
@3timeslazy any update on this?

**Comment by 3timeslazy** [comment]
@ziflex in progress
