### ISSUE TITLE
Redirection and WAIT_NAVIGATION problems

### ISSUE THREAD

**Issue by PierreBrisorgueil** [MontFerret/ferret#399]
hello i have some problems with redirects.

**My case** : I run a search that goes through a redirect page for a random time before arriving on the search result page.
`click -> redirect -> result`

**My tests (after click)**:

- `WAIT_NAVIGATION (doc, 5000)` => sometimes work, sometimes not, depend of the env & time : `node is either not visible or not an HTMLElement: FORpageNumINPAGINATION(doc,btnNext)` (next action)
- `WAIT_NAVIGATION (doc, 5000) WAIT_NAVIGATION (doc, 5000)` work, but no execution of the next action, like if it wait another navigation (first was'nt catch ?)
- `WAIT(1000) WAIT_NAVIGATION (doc, 5000)` sometimes ok, sometimes not, depend of the machine internet speed, redirection speed ..  :/ always failed 
- `WAIT(10000)` genrally ok, extra wait, but not reliable 

**Reproduction** : 

i made a link for that : http://waos.ovh/redirect.html
click -> redirect -> end 

redirect.html
`<a class="click" href="./redirect1.html">Second Step</a>`

redirect1.html
```
<head>
        <meta http-equiv="refresh" content="1;URL=./redirect2.html"></meta>
</head>
```

redirect2.html
`<h2 class="title">This is redirection end</h2>`

.fql
```
LET doc = DOCUMENT("http://waos.ovh/redirect.html", {
    driver: 'cdp',
    viewport: {
        width: 1920,
        height: 1080
    }
})

CLICK(doc, '.click')

WAIT_NAVIGATION(doc)

RETURN ELEMENT(doc, '.title')
```

- `WAIT_NAVIGATION(doc) ` -> null
- `WAIT_NAVIGATION(doc) WAIT_NAVIGATION(doc)` -> null
- `WAIT(1100) WAIT_NAVIGATION(doc)` -> Failed to execute the query operation timed out: WAIT_NAVIGATION(doc) at 12:0
- `WAIT(900) WAIT_NAVIGATION(doc)` -> null
- `WAIT(3000)` -> null
- `WAIT_NAVIGATION(doc, 5000) WAIT_ELEMENT(doc, '.title', 5000)` ->` cdp.Runtime: Evaluate: rpc error: Cannot find context with specified id (code = -32000): WAIT_ELEMENT(doc,'.title',5000) at 12:0`

**Comment by ziflex** [comment]
Thanks for the link!

**Comment by ziflex** [comment]
I'm planning to re-write this part of Ferret and thus, I'm thinking how to extend its capabilities.
@ap0 I remembered that you mentioned this in #302:
> A nice to have feature would be something like “navigate to a URL and wait for it to get to this other URL after a series of redirections”

I think this is a good time to discuss it.

**Comment by ziflex** [comment]
The main question I have is whether Ferret should figure these redirects out itself or user should provide some kind of hints how to handle "load page event"? 
For example, it could be like
``WAIT_NAVIGATION(url, { timeout: 5000, targetUrl: "some target url"})``

**Comment by PierreBrisorgueil** [comment]
@ziflex 
hum, it seems difficult to me to manage all the cases in ferret. Maybe something like waiting for regex URL, or URL contains until timeout?

**Comment by PierreBrisorgueil** [comment]
some news about this O.O ? :)

**Comment by ziflex** [comment]
Almost finished it!
