### ISSUE TITLE
how to access cli params from fql file?

### ISSUE THREAD

**Issue by tjombka** [MontFerret/ferret#404]
I can't find any example how to invoke CLI query parameter inside fql file. 

Please let me know how to access "blablabla" inside [filename].fql after:
ferret [filename].fql --param=eav:\"blablabla\"

Thank you in advance for your help.
tj

**Comment by ziflex** [comment]
Hi @tjombka,

you can access to params using their name  starting with ``@`` symbol. For example:

```
RETURN LOWER(@eav)
```
