### ISSUE TITLE
How to pass chrome cli switches (options) to docker container?

### ISSUE THREAD

**Issue by zmajew** [MontFerret/ferret#411]
Hi,
Thanks for everything.
Please, can you help me? 
I am running chrome in Ubuntu with:
`google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 --force-device-scale-factor=1 --no-first-run --no-default-browser-check --window-size="1280,813"  --no-sandbox http://www.chromestatus.com`
My question is: How to run docker container from the alpeware/chrome-headless-stable image and pass chrome options, for example --window-size="1280,813"?

`docker run -d -p=127.0.0.1:9223:9222 --name=google-chrome-stable -v /tmp/chromedata/:/data alpeware/chrome-headless-stable ????`

**Comment by ziflex** [comment]
Hey,

try to pass it as ``CHROME_OPTS`` env variable.
You can see [here](https://github.com/alpeware/chrome-headless-stable/blob/master/start.sh#L8) how it's used.

**Comment by zmajew** [comment]
Thaks!
