### ISSUE TITLE
How to run chrome with --proxy-server 

### ISSUE THREAD

**Issue by zmajew** [MontFerret/ferret#412]
I need help with running chrome with CLI --proxy-server settings.
When I set up a proxy server **from chrome GUI settings** (Settings/Advanced/Open your computer's proxy settings/Use manually specified proxy configuration) **it works fine** (checked on whatismyproxy.com). 
But, when I **set the proxy from command line** chrome **does not load any page**:

`google-chrome --proxy-server="https://206.246.75.178:3129"`

The same (main) problem is with headless or with dockerised alpeware/chrome-headless-stable:

`google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 --force-device-scale-factor=1 --no-first-run --no-default-browser-check  --no-sandbox http://www.chromestatus.com --proxy-server="https://206.246.75.178:3129"`

Have anyone experienced this problem?
I am using Kubuntu.
Thanks

**Comment by bundleman** [comment]
@zmajew Hit, try this env var as CHROME_OPTS=--proxy-server=your proxy

**Comment by ziflex** [comment]
Feel free to reopen.
