### ISSUE TITLE
how to capture the new page 's html source of "onclick=js-func target=_blank"

### ISSUE THREAD

**Issue by kaixinbuyu** [MontFerret/ferret#415]
a list page contains 10 list urls to new detail pages by "onclick=javascriptxxx target=_blank",
and each detail page's url will not change(xxxcom/xx=action.do).

so how to capture the new opened detail page's html source?
Can ferret's auto create detail page's document when new chrome-page tab openning?

**Comment by ziflex** [comment]
At this moment Ferret does not handle pages opened by JS.

**Comment by ziflex** [comment]
It can be a future feature, though.

**Comment by kaixinbuyu** [comment]
tks.I'll try to look for chrome's protocol to figure it out.
