### ISSUE TITLE
Get content from details pages

### ISSUE THREAD

**Issue by hubitor** [MontFerret/ferret#419]
Starting from a listing with links I would like to get some content from the details pages and paginate.

Say, I would like to get the titles for each link from here:
[https://gtmetrix.com/top1000.html](https://gtmetrix.com/top1000.html)

If I run this:

```
LET doc = DOCUMENT("https://gtmetrix.com/top1000.html", {
    driver: "cdp",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36"
})
WAIT_ELEMENT(doc, '.t1k-rank.sorting_1', 10000)
LET tblock = ELEMENT(doc, 'tbody')
LET blocks = ELEMENTS(tblock, 'a')

LET links = (
    FOR link IN blocks
        RETURN link
)

RETURN links
```

I get this Array:

`["http://www.facebook.com/","http://www.yahoo.com/","http://www.live.com/","http://www.wikipedia.org/","http://www.msn.com/","http://www.microsoft.com/","http://www.blogspot.com/","http://www.baidu.com/","http://www.qq.com/","http://www.mozilla.com/","http://www.sina.com.cn/","http://www.wordpress.com/","http://www.bing.com/","http://www.adobe.com/","http://www.163.com/","http://www.taobao.com/","http://www.soso.com/","http://www.twitter.com/","http://www.youku.com/","http://www.ask.com/","http://www.sohu.com/","http://www.amazon.com/","http://www.windows.com/","http://www.ebay.com/","http://www.yahoo.co.jp/"]`

I also get the same result if I use:
`RETURN link.innerText`

Now if I continue with this: 

```
FOR link IN links
    NAVIGATE(doc, link, 60000)
    LET texter = ELEMENT(doc, 'title')
    RETURN texter
```

in the first case I get this error:

```
Failed to execute the query
invalid type: expected [string], but got HTMLElement: NAVIGATE(doc,link,60000) at 31:4: FORlinkINlinksNAVIGATE(doc,link,60000)LETtexter=ELEMENT(doc,'title')RETURNtexter at 29:0
```

and in the second case I get this error:

```
Failed to execute the query
operation timed out: NAVIGATE(doc,link,60000) at 31:4: FORlinkINlinksNAVIGATE(doc,link,60000)LETtexter=ELEMENT(doc,'title')RETURNtexter at 29:0
```

1. In both cases the result leads to the assumption that `link` is a string. Is there a way to check the type?
2. Why the code does not work? Is this a time issue?
3. How can I tell ferret to wait for the details pages to load?

**Comment by ziflex** [comment]
Hey, thank you for giving Ferret a try!

> I get this Array:

> ["http://www.facebook.com/","http://www.yahoo.com/","http://www.live.com/","http://www.wikipedia.org/","http://www.msn.com/","http://www.microsoft.com/","http://www.blogspot.com/","http://www.baidu.com/","http://www.qq.com/","http://www.mozilla.com/","http://www.sina.com.cn/","http://www.wordpress.com/","http://www.bing.com/","http://www.adobe.com/","http://www.163.com/","http://www.taobao.com/","http://www.soso.com/","http://www.twitter.com/","http://www.youku.com/","http://www.ask.com/","http://www.sohu.com/","http://www.amazon.com/","http://www.windows.com/","http://www.ebay.com/","http://www.yahoo.co.jp/"]

> I also get the same result if I use:
> ``RETURN link.innerText``

In the first example, you have an array of HTMLElement and in the second one, you have an array of strings.
The reason why you are getting the same result is when a Ferret program returns a query result (a runtime value), it gets serialized into a JSON string and when a serialized representation of a HTMLElement is its inner text.

> Now if I continue with this:

> ```
> FOR link IN links
>     NAVIGATE(doc, link, 60000)
>     LET texter = ELEMENT(doc, 'title')
>     RETURN texter
> ```

> in the first case I get this error:

> ``Failed to execute the query invalid type: expected [string], but got HTMLElement: NAVIGATE(doc,link,60000) at 31:4: FORlinkINlinksNAVIGATE(doc,link,60000)LETtexter=ELEMENT(doc,'title')RETURNtexter at 29:0
``

It's an expected behavior, since you are not passing a string.

> and in the second case I get this error:

> ``Failed to execute the query
operation timed out: NAVIGATE(doc,link,60000) at 31:4: FORlinkINlinksNAVIGATE(doc,link,60000)LETtexter=ELEMENT(doc,'title')RETURNtexter at 29:0``

I'm testing it right now and what I see is that containerized Chrome is crashing:

```
[1122/030003.442950:ERROR:broker_posix.cc(46)] Received unexpected number of handles
[1122/030003.444703:ERROR:broker_posix.cc(46)] Received unexpected number of handles
[1122/030003.446711:ERROR:broker_posix.cc(46)] Received unexpected number of handles
[1122/030003.448462:ERROR:broker_posix.cc(46)] Received unexpected number of handles
[1122/030003.567290:ERROR:broker_posix.cc(46)] Received unexpected number of handles
[1122/030003.569734:ERROR:broker_posix.cc(46)] Received unexpected number of handles
[1122/030003.578482:ERROR:broker_posix.cc(46)] Received unexpected number of handles
[1122/030010.582430:ERROR:broker_posix.cc(46)] Received unexpected number of handles
[1122/030010.583671:FATAL:memory.cc(22)] Out of memory. size=262144
[1122/030010.594998:ERROR:broker_posix.cc(46)] Received unexpected number of handles
[1122/030010.705894:ERROR:broker_posix.cc(46)] Received unexpected number of handles
--2019-11-22 03:00:10--  https://clients2.google.com/cr/report
Resolving clients2.google.com (clients2.google.com)... 172.217.13.78, 2607:f8b0:4004:815::200e
Connecting to clients2.google.com (clients2.google.com)|172.217.13.78|:443... [1122/030010.753647:FATAL:memory.cc(22)] Out of memory. size=3664672
connected.
Failed to generate minidump.Parent failed to complete crash dump.
Illegal instruction
```

**Comment by ziflex** [comment]
For titles, you may try to use static driver:

```
LET doc = DOCUMENT("https://gtmetrix.com/top1000.html", {
    driver: "cdp"
})
WAIT_ELEMENT(doc, '.t1k-rank.sorting_1', 10000)
LET tblock = ELEMENT(doc, 'tbody')
LET blocks = ELEMENTS(tblock, 'a')

LET links = (
    FOR link IN blocks
        RETURN link.innerText
)

FOR link IN links
   LIMIT 14
     PRINT(link)
    // in memory driver
    LET doc2 = DOCUMENT(link, {
        driver: "http"
    })

    RETURN INNER_TEXT(doc2, 'title')
```

But there is another problem - some of the websites return 403 code and Ferret at this moment does not let you to handle this gracefully.

**Comment by ziflex** [comment]
[This](https://stackoverflow.com/questions/50701824/limit-chrome-headless-cpu-and-memory-usage) might useful.
In general, Chrome is surprisingly unstable in headless mode.

**Comment by hubitor** [comment]
Thanks for ferret and the quick reply!

Now I'm trying to learn how to paginate and specifically how pagination with recursion and end condition(s) work. The best I could do so far is to get content from the first page multiple times. The 2 examples on GitHub as well as the example from the blog:  [https://www.montferret.dev/blog/say-hello-to-ferret/](https://www.montferret.dev/blog/say-
hello-to-ferret/)

don't work. I get either timeouts or the selectors don't work.

This is a simplified version of my script:

```
LET doc = DOCUMENT("https://gtmetrix.com/top1000.html", {
    driver: "cdp"
})
WAIT_ELEMENT(doc, '.t1k-rank.sorting_1', 10000)
LET resultListSelector = 'tbody'
LET nextBtnSelector = 'a.paginate_button.next'
LET rowElmArr = ELEMENTS(doc, 'tr[role="row"]')

LET result = (
    FOR pageNum IN PAGINATION(doc, nextBtnSelector)
        LIMIT 2
        LET wait = pageNum > 0 ? WAIT_ELEMENT(doc, '.t1k-rank.sorting_1', 10000)  : false
        LET waitSelector = wait ? WAIT_ELEMENT(doc, resultListSelector) : false
        FOR rowElm IN rowElmArr
            RETURN INNER_TEXT(rowElm, '.t1k-url')
)

RETURN result
```

which gets 2 times the same content from the first page and not moving to the next page.
