### ISSUE TITLE
XPath and jQuery Selectors support in the functions

### ISSUE THREAD

**Issue by hubitor** [MontFerret/ferret#427]
**Is your feature request related to a problem? Please describe.**

All provided functions (e.g. PAGINATION()) in ferret support only CSS Selectors and these cannot cover all use cases.
For example, in:
[https://www.foxsports.com/nfl/players](https://www.foxsports.com/nfl/players)
I wanted to select the next button based on the text ("Next"), but selecting an element based on the text as I've seen isn't supported by CSS selectors.

**Describe the solution you'd like**

It would be better to support XPath and jQuery Selectors in the functions and give the user the option to choose the type of selectors he wants to use.

E.g.:
`LET nextBtnSelectorElement = XPATH(doc, "//a[contains(text(),'Next')]")`
and then:
`FOR pageNum IN PAGINATION(listingPage, nextBtnSelectorElement, "xpath")`

**Comment by ziflex** [comment]
Hey, I was thinking about during ``XPATH`` implementation. 
But I didn't find a good API for it. Like, passing ``xpath`` extra parameter does look elegantly. 
But I hope we can get back to it again in the future

**Comment by ziflex** [comment]
Will be available in v0.16.0
