### ISSUE TITLE
Run go get getting error. What is this?

### ISSUE THREAD

**Issue by BelodedAleksey** [MontFerret/ferret#430]
# github.com/MontFerret/ferret/pkg/drivers/cdp
go\src\github.com\MontFerret\ferret\pkg\drivers\cdp\driver.go:31:12: undefined: target.BrowserContextID

**Comment by ziflex** [comment]
Hey,
I guess you are not using Go modules and pulling from the master which means Go is pulling the latest version of [CDP](github.com/mafredri/cdp) which is not supported yet.

**Comment by ziflex** [comment]
Now it should be fixed.
