### ISSUE TITLE
element detached: INNER_HTML(doc,'html')

### ISSUE THREAD

**Issue by Daan-** [MontFerret/ferret#442]
**Describe the bug**
When running my script I run into the 'element detached' error after 2 loops.
The same logic for another website does work. Error is:
element detached: INNER_HTML(doc,'html') at 24:25: 

**To Reproduce**
```
LET match_urls = (
    FOR match IN ELEMENTS(doc, 'table[frame=lhs] a')
        RETURN CONCAT("<FULL URL>", match.attributes.href)
)

LET unique_match_urls = UNIQUE(match_urls)

LET links = (
    FOR match_url IN unique_match_urls
        WAIT(RAND(1000))
        NAVIGATE(doc, match_url, 20000)
        WAIT(RAND(1000))

        LET match_html = INNER_HTML(doc, 'html')
        WAIT(RAND(1000))

        NAVIGATE_BACK(doc)
        WAIT(RAND(1000))
        RETURN {url: match_url, html: match_html}
)
```
--

I added the RAND(1000) for debugging purposes.

**Expected behavior**
I expect for every loaded URL the HTML returned.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chrome 79.0.3945.117
 - Version: latest from master

**Additional context**
If I replace the loop with a DOCUMENT call like this, the code works (although very inefficiently by opening a new tab for every page):
```
LET links = (
    FOR match_url IN unique_match_urls
        WAIT(RAND(1000))
        LET inner_doc = DOCUMENT(match_url, {
            driver: "cdp",
            userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36",
            keepCookies: false
        })

        WAIT(RAND(1000))

        LET match_html = INNER_HTML(inner_doc, 'html')
        WAIT(RAND(1000))

        NAVIGATE_BACK(doc)
        WAIT(RAND(1000))
        RETURN {url: match_url, html: match_html}
)
```

**Comment by ziflex** [comment]
Hey @Daan- , thanks for giving Ferret a try.
Could you give us more context to reproduce the error?

**Comment by Daan-** [comment]
I will try to give some more context. My use case is collecting the raw HTML from a collection of URLs starting with a specific web page. Basically I just use Ferret for the retrieval part, the HTML I parse later.

My Chrome command line:
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9222 --no-first-run --no-default-browser-check --disable-features=TranslateUI --user-data-dir=chrome-datadir

Code to start Ferret:

	content, err := ioutil.ReadFile(fqlFileName)
	if err != nil {
		return nil, err
	}

	fqlFileContent := string(content)

	comp := compiler.New()

	program, err := comp.Compile(fqlFileContent)

	if err != nil {
		return nil, err
	}

	// create a root context
	ctx := context.Background()

	// enable HTML drivers
	// by default, Ferret Runtime does not know about any HTML drivers
	// all HTML manipulations are done via functions from standard library
	// that assume that at least one driver is available
	ctx = drivers.WithContext(ctx, cdp.NewDriver())
	ctx = drivers.WithContext(ctx, http.NewDriver(), drivers.AsDefault())
	out, err := program.Run(ctx,
		runtime.WithLogLevel(logging.DebugLevel),
	)

	if err != nil {
		return nil, err
	}

The full fql file (in the mean time I added some things):

LET doc = DOCUMENT("<URL>", {
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36",
    keepCookies: false
})

LET match_urls = (
    FOR match IN ELEMENTS(doc, 'table[frame=lhs] a')
        FILTER CONTAINS(match.attributes.href, '&match')
        FILTER !CONTAINS(match.attributes.href, '&results')
        FILTER !CONTAINS(match.attributes.href, '&stageresults')
        FILTER !CONTAINS(match.attributes.href, '&verify')
        FILTER !CONTAINS(match.attributes.href, '&cert')
        RETURN CONCAT("<URL>", match.attributes.href)
)

LET unique_match_urls = UNIQUE(match_urls)

LET links = (
    FOR match_url IN unique_match_urls
        WAIT(RAND(1000))
        NAVIGATE(doc, match_url, 20000)
        WAIT(RAND(1000))

        LET match_html = INNER_HTML(doc, 'html')
        WAIT(RAND(1000))

        NAVIGATE_BACK(doc)
        WAIT(RAND(1000))
        RETURN {url: match_url, html: match_html}
)

RETURN links


I made sure to not reuse elements from the doc in future navigation (to prevent this from happening), however it seems like INNER_HTML is looking at an older reference of doc (don't know if that's possible), or something else is off about that.
If needed I can send the actual URL in private.

**Comment by Daan-** [comment]
Hope that gives some context, let me know if you need more info.

**Comment by ziflex** [comment]
The target url would be helpful.
You can send it to me privately [here](https://discordapp.com/channels/501533080880676864/501533080880676866).

**Comment by Daan-** [comment]
It does not seem to work (tried on desktop and mobile)...
(My email is firstname + company url)

**Comment by ziflex** [comment]
Sorry, [here](https://discord.gg/kzet32U) is a correct link.
