### ISSUE TITLE
Proxy in cdp

### ISSUE THREAD

**Issue by bundleman** [MontFerret/ferret#443]
Hi all!
I have tried to use option cdp.WithProxy("some proxy") , but it doesn't work, chrome has Ignored this option.
Maybe I'm doing something wrong?

**Comment by ziflex** [comment]
Hey, Chrome does not allow to set proxy during runtime. The only way to set proxy is during launch.
```
google-chrome --proxy-server="socks5://127.0.0.1:1080"
```

**Comment by bundleman** [comment]
@ziflex Oh, so I thought (, but thanks! So, maybe then use an approach like this module https://github.com/chromedp/chromedp when chrome launch from code ?. There it is possible to specify the option ProxyServer

**Comment by ziflex** [comment]
You can use ``--cdp-launch`` flag to launch Chrome. But it won't pass proxy values.
PR is welcome :)

**Comment by bundleman** [comment]
@ziflex How i can do it from code using Ferret? It's no PR, I just want to use only one module, not many.

**Comment by ziflex** [comment]
@bundleman sorry, missed your message.

You can use [this module](https://github.com/MontFerret/ferret/tree/master/cli/browser).

**Comment by bundleman** [comment]
@ziflex Thanks!
