### ISSUE TITLE
Scrapping on Infinite Scroll Page

### ISSUE THREAD

**Issue by okzapradhana** [MontFerret/ferret#445]
**Is your feature request related to a problem? Please describe.**
I had problem how to scrap on infinite scroll page. Using `FOR num in 1..n` didn't solve my problem because on some day the data will increased and appended to page.

**Describe the solution you'd like**
I hope there will be `function` or `command` to get `height` of page. E.g on `javascript` we could use `document.body.scrollHeight`. I have searched everywhere on this repo but hadn't find one yet.
And `WHILE TRUE` as well to check the condition after each scroll.

**Describe alternatives you've considered**
Whats in my mind for this time the solution will need `WHILE TRUE` syntax and get current `height` of page. I get inspired from `selenium` (reference: https://dev.to/hellomrspaceman/python-selenium-infinite-scrolling-3o12)

**Additional context**
If there are solutions currently related to my problem, please kindly inform me. I would be really thankful and appreciated. 

Thanks!

**Comment by ziflex** [comment]
Hey,

there is a backlog item for ```WHILE``` loop, but it will be added in the future releases (not in this upcoming 0.10.0).

Meanwhile, you can play with functions like ``SCROLL_TOP`` and ``SCROLL_BOTTOM``.

**Comment by okzapradhana** [comment]
> Hey,
> 
> there is a backlog item for `WHILE` loop, but it will be added in the future releases (not in this upcoming 0.10.0).
> 
> Meanwhile, you can play with functions like `SCROLL_TOP` and `SCROLL_BOTTOM`.

Thanks for response! Yes, I've saw the backlog yesterday and I've trying to play with and `SCROLL_BOTTOM` already. But still didnt solve my problem because there is no certain condition when to `stop` the `SCROLL_BOTTOM` actions.
