### ISSUE TITLE
cdp.Runtime: CallFunctionOn: rpc error: Argument should belong to the same JavaScript world as target object (code = -32000):

### ISSUE THREAD

**Issue by kaixinbuyu** [MontFerret/ferret#447]
getInnerHtml,setInnerHtml,getInnerText,setInnerText (in the same template (el, selector) => {... ) raise error : Argument should belong to the same JavaScript world as target object
`
func (el *HTMLElement) GetInnerHTMLBySelector(ctx context.Context, selector values.String) (values.String, error) {
	if el.IsDetached() {
		return values.EmptyString, drivers.ErrDetached
	}

	sel, err := selector.MarshalJSON()

	if err != nil {
		return values.EmptyString, err
	}

	out, err := el.exec.EvalWithArgumentsAndReturnValue(
		ctx,
		templates.GetInnerHTMLBySelector(),
		runtime.CallArgument{
			ObjectID: &el.id.ObjectID,
		},
		runtime.CallArgument{
			Value: sel,
		},
	)

	if err != nil {
		return values.EmptyString, err
	}

	return values.NewString(out.String()), nil
}

`

Both cli,fql raise this error.

**Comment by ziflex** [comment]
Could you give more information about what you are doing ?
