### ISSUE TITLE
Returning of private structs

### ISSUE THREAD

**Issue by 3timeslazy** [MontFerret/ferret#46]
Here returns the private struct _values.None_. Maybe it's better to make it public?
https://github.com/MontFerret/ferret/blob/7f00078076e3cee5432ef6374381158782e20280/pkg/stdlib/arrays/append.go#L16-L21

**Comment by ziflex** [comment]
@3timeslazy hi. The reason why it's private is that its value is singleton and not supposed to be initiated manually. In most cases ``Value`` interfaced used.
