### ISSUE TITLE
Add progress to large loops

### ISSUE THREAD

**Issue by Pangoraw** [MontFerret/ferret#469]
**Is your feature request related to a problem? Please describe.**
There is no easy way to see the progress of iterations over a large array. As I often use ferret by writing small `.fql` file and run them from the command line.

**Describe the solution you'd like**
Having progress printed to stderr maybe.

**Describe alternatives you've considered**
Printing to ferret.log with LOG

**Additional context**
In python, there is [tqdm](https://github.com/tqdm/tqdm#tqdm) which can wrap an array and print progress for each iterations, this could be useful to see the current progress of large iterations. I was thinking of something in the line of :
```
FOR element IN SHOW_PROGRESS(elements)
     WAIT(2)
     RETURN INNER_TEXT(element)
```
And the stderr output of the program could look something like this:
```
76%|████████████████████████        | 7568/10000 [00:33<00:10, 2.0s/it]
```
Anyway, thanks for this project :clap:

**Comment by ziflex** [comment]
I think the best way would be adding support of streams to Ferret runtime. That would give us possibility retrieve elements as soon as they get available during scraping process.

**Comment by ziflex** [comment]
[Look at this issue](https://github.com/MontFerret/ferret/issues/459)

**Comment by ziflex** [comment]
CLI was moved to another [repo](https://github.com/MontFerret/cli).
Feel free to reopen the issue there.
