### ISSUE TITLE
.../pkg/runtime/core/function.go:10: syntax error: unexpected = in type declaration

### ISSUE THREAD

**Issue by miclill** [MontFerret/ferret#47]
```bash
sam@debian ~ $ go version
go version go1.7.4 linux/amd64

```

Do I need a higher go version? In Readme it says go 1.6 should be sufficient.

**Comment by ziflex** [comment]
@miclill I guess, README is wrong in this statement. The lowest version that is used in Travis - 1.9.
I would stick to this one.
Will update the README file.
