### ISSUE TITLE
Embedded mode example is not working

### ISSUE THREAD

**Issue by jbampton** [MontFerret/ferret#473]
**Describe the bug**
The embedded mode example is not working
https://github.com/MontFerret/ferret#embedded-mode

**To Reproduce**
1. go run the file

**Expected behavior**
File produces data and does not error.

**Screenshots**
<img width="829" alt="Screen Shot 2020-04-21 at 1 20 14 am" src="https://user-images.githubusercontent.com/418747/79768614-60afda00-836e-11ea-9839-2616b99e5484.png">

**Comment by jbampton** [comment]
Seems to me the FQL is also wrong.  Running the query through the REPL gives an error.  
It seems the word `desc` is a reserved word.

<img width="672" alt="Screen Shot 2020-04-21 at 2 47 44 am" src="https://user-images.githubusercontent.com/418747/79777921-4d573b80-837b-11ea-9c4d-2cbab9ac82bb.png">

**Comment by ziflex** [comment]
> **Describe the bug**
> The embedded mode example is not working
> https://github.com/MontFerret/ferret#embedded-mode
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. go run the file
> 
> **Expected behavior**
> File produces data and does not error.
> 
> **Screenshots**
> <img alt="Screen Shot 2020-04-21 at 1 20 14 am" width="829" src="https://user-images.githubusercontent.com/418747/79768614-60afda00-836e-11ea-9839-2616b99e5484.png">

Hey, this has been fixed in the master. I will roll out a patch release this week.

**Comment by ziflex** [comment]
Hey, try [0.10.2](https://github.com/MontFerret/ferret/releases/tag/v0.10.2).

**Comment by jbampton** [comment]
Hey @ziflex I did try the latest release.

Found an issue https://github.com/MontFerret/ferret/pull/474
