### ISSUE TITLE
Messages in the terminal when updating

### ISSUE THREAD

**Issue by jbampton** [MontFerret/ferret#477]
**Describe the bug**
Try to update with `go get -u ./...`

**To Reproduce**
Run: `go get -u ./...`

**Expected behavior**
No warning messages

**Screenshots**
<img width="798" alt="Screen Shot 2020-04-21 at 7 25 22 am" src="https://user-images.githubusercontent.com/418747/79801563-a89c2480-83a1-11ea-899a-55f81103e0b8.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4

**Comment by ziflex** [comment]
Fixed by #495
