### ISSUE TITLE
Go vet fail when building using CirlceCI

### ISSUE THREAD

**Issue by yiss** [MontFerret/ferret#48]
When I build the project using CircleCI I'm getting this error for the command go vet :

> make build
> dep ensure
> go vet ./cmd/... ./pkg/...
> # github.com/{{ORG_NAME}}/{{REPO_NAME}}/pkg/runtime/values_test [github.com/{{ORG_NAME}}/{{REPO_NAME}}/pkg/runtime/values.test]
> pkg/runtime/values/array_test.go:266:10: invalid argument s (type *values.Array) for len
> pkg/runtime/values/array_test.go:267:8: invalid operation: s[0] (type *values.Array does not support indexing)
> pkg/runtime/values/array_test.go:271:10: invalid argument s2 (type *values.Array) for len
> Makefile:43: recipe for target 'vet' failed
> make: *** [vet] Error 2
> Exited with code 2

Any idea why ?

**Comment by ziflex** [comment]
Did you update the tests? I can't event find anything that would get values by index.

**Comment by yiss** [comment]
Just did and removed CircleCI, didn't see that TravisCI already works

**Comment by ziflex** [comment]
@yiss can I close the issue?

**Comment by yiss** [comment]
@ziflex yes
