### ISSUE TITLE
How to get rid of converted characters in URLs 

### ISSUE THREAD

**Issue by asitemade4u** [MontFerret/ferret#488]
I am developing a crawler and so far, so very good: thank you for this outstanding crawler.

The only issue is that, in the returned URLs, there is a `&` character which gets converted into `\u0026`, thus: `"https://thedomain/alphabet=M\u0026borough=Bronx"`

So I tried to replace it, either by using `SUBSTITUTE`:
```RETURN SUBSTITUTE(prfx + letter.attributes.href, "\u0026", "&")```

or `REGEX_REPLACE`.

In both cases, the `\u0026` string is NOT replaced and remains embedded into the resulting URLs.
However, when I try `SUBSTITUTE`say on `a` -> `z` it works fine.

Is it a limitation of JSON, which I use as an output format?
How can I get rid of the converted string as it prevents me from crawling at the lower levels of the website.

**Comment by ziflex** [comment]
Thank you and I'm glad that you like it!

I assume you are using ``cdp`` driver, right? If so, I think the problem is that CDP is encodes urls before sending it to Ferret since it's a JSON-based communication.
``DECODE_URI_COMPONENT`` is supposed to solve the problem but it seems not working:
```
Welcome to Ferret REPL
Please use `exit` or `Ctrl-D` to exit this program.
> RETURN DECODE_URI_COMPONENT("https://thedomain/alphabet=M\u0026borough=Bronx")
"https://thedomain/alphabet=M\\u0026borough=Bronx"
```

Therefore I mark it as a bug.

**Comment by asitemade4u** [comment]
Thank you for the response!

I have a related 2question as you just mentioned cdp.
I would like not to use it but I have not found a way to access the 
server which I do NOT host locally, but on a "real, physical" local 
server, under docker.

So, is there a way to connect to a remote server without resorting to CDP?

Currently, when executing a script, I do: ferret --cdp http://<the 
server ip>:9222 <thefile>.aql

Please also note I am using the AQL extension because the only VS Code 
plugin that formats and lints the language does not work with FQL, only AQL.

**Comment by ziflex** [comment]
Not sure I fully understand you.
CDP driver uses Chrome to communicate with web pages and you need it only if your target page is dynamically rendered and/or requires some user interaction to retrieve data you need.

**Comment by asitemade4u** [comment]
Sorry for being so obscure.

The question was: how do I connect to a remote Ferret server, hosted on 
a different IP address than localhost, from the cli?

Something like:

ferret --*host* http://<theserverip>:9222 <thescript>.aql

**Comment by ziflex** [comment]
Ah, well.
I think there is a misunderstanding going on :) Ferret CLI is an executable binary that already contains Ferret Runtime (they just happen to be in the same repo).
What you are referring to is a Chrome/Chromium with open remote debugging port that Ferret's CDP driver uses to perform web scraping of dynamic pages.

**Comment by asitemade4u** [comment]
You mean that the "Ferret Server" on docker I have installed on my local 
physical server is never used except with CDP?

And so, basically, I do not need it in cased I do NOT use CDP?

Wow, this is would be serious misunderstanding...

**Comment by asitemade4u** [comment]
and yet, I just tried to execute: `ferret <thescript>.aql > 
tst.jsonhost` and absolutely nothing happens...

**Comment by ziflex** [comment]
> You mean that the "Ferret Server" on docker I have installed on my local physical server is never used except with CDP? And so, basically, I do not need it in cased I do NOT use CDP? Wow, this is would be serious misunderstanding...

By "Ferret Server" do you mean [this project](https://github.com/MontFerret/ferret-server)?

> and yet, I just tried to execute: `ferret <thescript>.aql >
tst.jsonhost` and absolutely nothing happens...

Could you share your script? Hard to tell what's wrong without seeing actual code.

**Comment by asitemade4u** [comment]
Here you go:


        My docker-compose.yml file

``` yaml

version: "3"
services:
chrome-headless:
container_name: frt
image: alpeware/chrome-headless-stable
ports:
- "9222:9222"
restart: unless-stopped
volumes:
- "/home/stsinc/dkr/kuq-frt/dta:/data alpeware/chrome-headless-stable"

```


        the script I am executing:

LETdoc 
=DOCUMENT('https://www.nycgovparks.org/about/history/historical-signs', {
driver: "cdp"
})
LETprfx ='https://www.nycgovparks.org'
WAIT_ELEMENT(doc, 'div#logo_block.span2', 5000)
// Parse boro links
LETboros =ELEMENTS(doc, 'html body div#page div#maincontent div.row 
div.span9 main ul.text_list li a')
LETbrolnk =(
FORbro INboros
RETURNprfx +bro.attributes.href
)
// RETURN {brolnk}
// Then letter grid within each boro
// 20200429 Problem with the \u0026 encoded character of "&"
FORbro_link INbrolnk
NAVIGATE(doc, bro_link, 5000)
LETletters =ELEMENTS(doc, 'html body div#page div#maincontent div.row 
div.span9 main table tbody tr td div a')
LETltrlnk =(
FORletter INletters
RETURNSUBSTITUTE(prfx +letter.attributes.href, "\u0026", "&")
)
RETURNFLATTEN(ltrlnk)

**Comment by ziflex** [comment]
For this webpage you def do not need CDP. 
```
LET doc = DOCUMENT('https://www.nycgovparks.org/about/history/historical-signs')
LET prfx = 'https://www.nycgovparks.org'

// Parse boro links
LET boros = ELEMENTS(doc, 'html body div#page div#maincontent div.row div.span9 main ul.text_list li a')
LET brolnk = (
	FOR bro IN boros
		RETURN prfx +bro.attributes.href
)

// Then letter grid within each boro
// 20200429 Problem with the \u0026 encoded character of "&"
LET result = (FOR bro_link IN brolnk
    LET d = DOCUMENT(bro_link)
    LET letters = ELEMENTS(d, 'html body div#page div#maincontent div.row div.span9 main table tbody tr td div a')
	LET ltrlnk = (
		FOR letter IN letters
			RETURN DECODE_URI_COMPONENT(prfx +letter.attributes.href)
	)
	
	RETURN FLATTEN(ltrlnk)
)

RETURN FLATTEN(result)
```

**Comment by asitemade4u** [comment]
Great!
And what the CLI instruction will look like then?

⁣S.​

**Comment by ziflex** [comment]
```
ferret <thescript>.aql 
```

**Comment by asitemade4u** [comment]
Oh I get it now. There might be some additional explanations to provide in the doc...
Thank you SO MUCH!

⁣S.​

**Comment by ziflex** [comment]
Yeah, I will add some clarifications to the docs about differences between in-memory static pages and Chrome-driven pages.

**Comment by asitemade4u** [comment]
Thank you for the remodeled script. It works perfectly, except for the 
\u0026 issue which, unfortunately, is blocking as I am not able to get 
down one level...
