### ISSUE TITLE
strings.RandomToken is not working on Windows

### ISSUE THREAD

**Issue by 3timeslazy** [MontFerret/ferret#496]
**Describe the bug**
`strings.RandomToken` is not working on Windows

**To Reproduce**
1. Run `go test -v ./...`
2. Failure

**Expected behavior**
Tests passed

**Actual**
Failures

**Test log**
* C:/Users/vladimir fetisov/go/src/github.com/MontFerret/ferret/pkg/stdlib/strings/random_test.go
  Line 47:
  Expected     'XBFTNQVd'
  to NOT equal 'XBFTNQVd'
  (but it did)!
  goroutine 39 [running]:
        C:/Users/vladimir fetisov/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/reporting/reports.go:143 +0x74
        C:/Users/vladimir fetisov/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/reporting/reports.go:103 +0x73
        C:/Users/vladimir fetisov/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:176 +0xe6
        C:/Users/vladimir fetisov/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/doc.go:125 +0x6a
  github.com/MontFerret/ferret/pkg/stdlib/strings_test.TestRandomToken.func3()
        C:/Users/vladimir fetisov/go/src/github.com/MontFerret/ferret/pkg/stdlib/strings/random_test.go:47 +0x2d3
        C:/Users/vladimir fetisov/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/discovery.go:80 +0x2b
        C:/Users/vladimir fetisov/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:261 +0x128
        C:/Users/vladimir fetisov/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:110 +0xf5
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
        C:/Users/vladimir fetisov/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:97 +0x453
  github.com/jtolds/gls.EnsureGoroutineId.func1()
        C:/Users/vladimir fetisov/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:24 +0x35
  github.com/jtolds/gls._m(0x0, 0xc00022b160)
        C:/Users/vladimir fetisov/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:108 +0x38
  github.com/jtolds/gls.github_com_jtolds_gls_markS(0x0, 0xc00022b160)
        C:/Users/vladimir fetisov/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:56 +0x3c
  github.com/jtolds/gls.addStackTag(...)
        C:/Users/vladimir fetisov/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:49
  github.com/jtolds/gls.EnsureGoroutineId(0xc00022f2c0)
        C:/Users/vladimir fetisov/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:24 +0xf9
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc0000884c0, 0xc00022f260, 0xc00022b120)
        C:/Users/vladimir fetisov/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:63 +0x152
        C:/Users/vladimir fetisov/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:105 +0x22e
        C:/Users/vladimir fetisov/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/doc.go:75 +0xc5
  github.com/MontFerret/ferret/pkg/stdlib/strings_test.TestRandomToken(0xc0002350e0)
        C:/Users/vladimir fetisov/go/src/github.com/MontFerret/ferret/pkg/stdlib/strings/random_test.go:32 +0x190
  testing.tRunner(0xc0002350e0, 0x61aec8)
        c:/go/src/testing/testing.go:991 +0xe3
  created by testing.(*T).Run
        c:/go/src/testing/testing.go:1042 +0x35e

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Perhaps the problem is in the standard library

**Comment by ziflex** [comment]
Closed by #497
