### ISSUE TITLE
Adding space between parts of inner text

### ISSUE THREAD

**Issue by gormv** [MontFerret/ferret#500]
Hi

Is it possible to add space between parts of inner text. 

Lets say you have:

```html
<div>
	<span>1</span>
	<span>2</span>
</div>
````

INNER_TEXT(div) returns today '12', but is there some trick to return '1 2'?

**Comment by ziflex** [comment]
Hey,

Could you give a little bit more information about it?
What driver are using? Do you have same issue with another driver?

**Comment by gormv** [comment]
Hi, I see my example was formatted wrong. Here is the complete example:

````html
<div><span>1</span><span style="display:block">2</span></div><div>3<span style="display:block">4</span></div>
````

So the page this looks like when rendered

```
1
2
3
4
```

I scrape it with following FQL: 

```
LET els = ELEMENTS(doc, 'div')
FOR el in els
    RETURN INNER_TEXT(el)
```

Then it becomes:

`["12", "34"]`

But what I want is:

`["1 2", "3 4"]`

I tested something like this:

```
LET els = ELEMENTS(doc, 'div')
LET txts = (
    FOR el in els
        RETURN {
                  a: INNER_TEXT(el),
                  b: CONCAT_SEPARATOR(' ', INNER_TEXT_ALL(el, 'span')),
        }
)
FOR txt IN txts
    RETURN LENGTH(txt.a) > LENGTH(txt.b) ? txt.a : txt.b
```

Which returns `["1 2", "34"]`

But as I understand it, it's no way to querySelectorAll on text nodes, so the 3 is a bit tricky.

I know the html here is a bit tricky and this is a bit of edge case with the CSS block style on <span> but just wanted to see if anyone had any suggestions on other approaches I could try or spot some obvious lack of understanding.

**Comment by ziflex** [comment]
> Hi
> 
> Is it possible to add space between parts of inner text.
> 
> Lets say you have:
> 
> ```
> <div>
> 	<span>1</span>
> 	<span>2</span>
> </div>
> ```
> 
> INNER_TEXT(div) returns today '12', but is there some trick to return '1 2'?

Ok, after more close review I would not call it a bug since it's a natural behavior.

**Comment by ziflex** [comment]
> Hi, I see my example was formatted wrong. Here is the complete example:
> 
> ```
> <div><span>1</span><span style="display:block">2</span></div><div>3<span style="display:block">4</span></div>
> ```
> 
> So the page this looks like when rendered
> 
> ```
> 1
> 2
> 3
> 4
> ```
> 
> I scrape it with following FQL:
> 
> ```
> LET els = ELEMENTS(doc, 'div')
> FOR el in els
>     RETURN INNER_TEXT(el)
> ```
> 
> Then it becomes:
> 
> `["12", "34"]`
> 
> But what I want is:
> 
> `["1 2", "3 4"]`
> 
> I tested something like this:
> 
> ```
> LET els = ELEMENTS(doc, 'div')
> LET txts = (
>     FOR el in els
>         RETURN {
>                   a: INNER_TEXT(el),
>                   b: CONCAT_SEPARATOR(' ', INNER_TEXT_ALL(el, 'span')),
>         }
> )
> FOR txt IN txts
>     RETURN LENGTH(txt.a) > LENGTH(txt.b) ? txt.a : txt.b
> ```
> 
> Which returns `["1 2", "34"]`
> 
> But as I understand it, it's no way to querySelectorAll on text nodes, so `"34"` is a bit tricky.
> 
> I know the HTML here is a bit is a bit of edge case with the CSS block display on `<span>`. Just wanted to see if anyone had any suggestions on other approaches I could try or spot some obvious lack of understanding in FQL/ferret.

Why don't you get inner html of span elements instead of their parent?

**Comment by ziflex** [comment]
Try this
```
LET doc = PARSE('<div><span>1</span><span style="display:block">2</span></div><div>3<span style="display:block">4</span></div>')

LET result = (
	FOR div IN ELEMENTS(doc, "div")
	    RETURN XPATH(div, "//text()")
	)

FOR pair IN result
	RETURN CONCAT_SEPARATOR(" ", pair)
```
