### ISSUE TITLE
Scraping <script type="text/javascript">

### ISSUE THREAD

**Issue by freeo** [MontFerret/ferret#502]
Is it already supported/planned to work with the inner text of the `<script>` field? 

Example:
My FQL script template receives the script like this:
``` AQL
LET root_doc_selector = 'html'
LET doc = DOCUMENT("{{ .URL }}", { driver: "cdp" })

WAIT_ELEMENT(doc, root_doc_selector, 5000)
FOR everything IN ELEMENTS(doc, root_doc_selector)
  FOR js IN ELEMENTS(everything, "script")
    RETURN {
      tralbum: js,
    }
```

The unformatted inner text then looks like this:
```
"\n\nvar BandData = {\n    id: 3727389256,\n    name: \"myname\",\n    fan_email: null,\n    account_id: 50164,\n    has_discounts: null,\n    image_id: 17378\n};\n\nvar EmbedData = {\n    tralbum_param: { name: \"album\", value: 312933 }, \n    album_title: \"Cube\",\n    linkback: \"http://mysite.com\" + \"/album/cube\",\n    art_id: 731444,\n    artist: \"someartist\",\n    swf_base_url: \"https://mysite.com\",\n    show_campaign: null, \n    embed_info: {\"public_embeddable\":\"09 May 2020 16:00:20 GMT\",\"item_public\":true,\"no_track_preorder\":false,\"exclusive_embeddable\":null}\n}
```

But as can be seen theres simple JSON data in there.

I would like to select those JSON objects directly by their name in FQL. Like this:
```
     LET band = ELEMENT(tr, "script[BandData]")
```
And then be able to use it like a regular element:
```
    LET id = band.id
```

What do you think? Is it worth to have it in ferret or should users just work with regex within <script>? I think extracting the var's (json's) is general enough to justify that. What would be the starting point for that?

**Comment by ziflex** [comment]
At this moment, there is no such functionality. But you may try to use XPATH or REGEX to extract the json.
