### ISSUE TITLE
Embedable Option Launch Chrome

### ISSUE THREAD

**Issue by Fborgeslc** [MontFerret/ferret#504]
Hi, 

First of all congrats for the amazing work, I have two questions that I don't know if Ferret supports it.

1. Can chrome be launched from this mode. Something like check if chrome is running and if not launch it

2. Can we maintan a session between executions? Let's imagine that we make a login in a certain page and then we want to use that session to execute several scripts, splitted in time ..

Thanks 

Fiipe

**Comment by ziflex** [comment]
Hey, thank you!
1. Yes, you can use [this package](https://github.com/MontFerret/ferret/tree/master/cli/browser) from CLI.
2. At this moment, there is no session support (can be a good feature request!). But you can set cookies (saved earlier) for session-based pages during page initialization. Examples of how to use cookies, you can find [here](https://github.com/MontFerret/ferret/tree/master/e2e/tests/dynamic/doc/cookies).
