### ISSUE TITLE
Auto generate ferret stdlib documentation

### ISSUE THREAD

**Issue by ksdme** [MontFerret/ferret#510]
I don't see any documentation for the standard library on the website. Because the entire stdlib is in Go anyway, we should be able to use godoc or some other equivalent static tool to turn the doc comments on the methods to generate documentation with theme at https://www.montferret.dev/.

PS: I am open to picking up this issue.

**Comment by ziflex** [comment]
Hey,
it' a great idea and we have been thinking about it for a while. You can surely pick it up!

**Comment by ksdme** [comment]
Great, I'll start working on it.

**Comment by ksdme** [comment]
Here's my primitive research (I have not tested any of these approaches in any capacity as of yet),

1. `go doc` seems too inflexible for this use case. It looks to me like we cannot have it generate documentation for specific packages and also that it relies on showing the function signatures to document it's arguments and return type which hardly suits us.

2. We could have a cli program that imports ferret, reflects on the namespace that the ferret compiler has and generate a list of all the stdlib methods along with their go file names (looks like it's possible) and then have a separate static tool build a yaml/json in some standard structure and use it to template the docs.

3. Another easier way would be to fix the documentation of the stdlib functions to also indicate the names that they register themselves into namespace with and build a simple tool to extract the comments and struture them by looking at the entire code (no static analysis of go code would be required) and then follow the same method as mentioned in 2 to template the docs. This approach relies on the related comments in the codebase being rich and bringing along required metadata, so we might get a chance to actually improve the comments while doing this.

What do you think @ziflex?

**Comment by ziflex** [comment]
Hey, thanks for the analysis. I like the 3rd option.
Even though, it won't be idiomatic, we could use something like [JS Doc](https://jsdoc.app/) or [JavaDoc](https://en.wikipedia.org/wiki/Javadoc).

**Comment by ksdme** [comment]
https://github.com/MontFerret/ferret/pull/513 generates internal representation required to generate docs as YAML.
