### ISSUE TITLE
DATE_COMPARE does not seem to be registered with a namespace

### ISSUE THREAD

**Issue by ksdme** [MontFerret/ferret#514]
`DATE_COMPARE` does not seem to be exposed.

https://github.com/MontFerret/ferret/blob/master/pkg/stdlib/datetime/lib.go
https://github.com/MontFerret/ferret/blob/master/pkg/stdlib/datetime/compare.go#L18

**Comment by 3timeslazy** [comment]
@ksdme you're right, we forgot to add `DATE_COMPARE` into `lib.go`. Want to do PR?

**Comment by ksdme** [comment]
Sure thing
