### ISSUE TITLE
CDP driver does not close tabs

### ISSUE THREAD

**Issue by ziflex** [MontFerret/ferret#518]
Whenever CLI process gets interrupted or killed, CDP driver must (and used to) close all open tabs.
It stopped doing this.

**Comment by Pangoraw** [comment]
I am interested in solving this one. It should close tabs when handling signals like SIGTERM sent with `kill -TERM <PID>` ? 
For me when running CTRL+C the tabs close.

**Comment by ziflex** [comment]
> I am interested in solving this one. It should close tabs when handling signals like SIGTERM sent with `kill -TERM <PID>` ?
> For me when running CTRL+C the tabs close.

Hmm... I might spend more time on this but when I was working on [lab](https://github.com/MontFerret/lab) I have noticed when I interrupted execution, tabs remained open. Then I tested it via REPL and got same effect.
