### ISSUE TITLE
DSL for different languages

### ISSUE THREAD

**Issue by Hedgehogues** [MontFerret/ferret#519]
Is there python dsl language like ferret?

**Comment by ziflex** [comment]
Maybe? I do not know. 
Syntax and grammar definitions are out there for parser generation, so if anyone want to implement the runtime, they are very welcome :)

**Comment by Hedgehogues** [comment]
This is a very long way. I want to do it by one-two-three week.

**Comment by ziflex** [comment]
It really depends on your use case.
You can try to use [this tool](https://github.com/go-python/gopy) to generate CPython extension off the Ferret runtime. But it's a hardcore way.
Maybe a simple dedicated HTTP service would be enough? If so, you can use [this project](https://github.com/MontFerret/worker) for that.

**Comment by Hedgehogues** [comment]
What about swagger for thi

**Comment by Hedgehogues** [comment]
- What about swagger into service?
- Transform from golang to python is a problem. I will have a trouble with `struct`.

**Comment by ziflex** [comment]
The service has just 3 simple endpoints (2 of them are mostly informative).
Index route (``/``) expects a POST request with the following shape a of a payload:
```
{
        text: string
        params?: map<string, any>
}
```

But you are right, I need to document that service better :)
