### ISSUE TITLE
Re-use browser tab between distinct queries

### ISSUE THREAD

**Issue by acco** [MontFerret/ferret#529]
First - love this project, thank you :)

**Is your feature request related to a problem? Please describe.**

Running Ferret in embedded mode, I'll often run queries inside of a loop like this:

```
query := fmt.Sprintf(`LET doc = DOCUMENT("%s", { driver: "cdp" })
// work on document
`, url)
```

So I'm running control logic outside of Ferret/FQL, dipping into Ferret to perform scraping/querying.

Problem is: When I'm running this on my computer, every time my Go program executes the FQL query, it creates a new browser tab and executes. Every time a new Chrome tab is launched, macOS pulls Chrome into focus/the foreground. This means whatever task I'm performing is interrupted. 

**Describe the solution you'd like**

To be able to instantiate a new browser tab and re-use it for each distinct FQL execution. I think this will mean I can keep Chrome churning in the background.

**Describe alternatives you've considered**

I'm not sure there's a way to do this now? I tried poking through the source code - if there is a way, a couple hints are all I need!

**Additional context**

* macOS
* embedded Ferret in a Go program

**Comment by ziflex** [comment]
Hey, I'm glad you love the project, thank you!

At this moment, there is no such functionality, but it's not very difficult to add it.
There is a [function](https://github.com/MontFerret/ferret/blob/master/pkg/drivers/cdp/driver.go#L107) in CDP driver that opens a new tab on every ``DOCUMENT()`` function call. [Here is an example of how a new tab is created](https://github.com/MontFerret/ferret/blob/ad24814efdc1264ff43b41b5461f74362dbd25c7/pkg/drivers/cdp/driver.go#L123).

Since you are using Ferret in embedded mode, what you can do is that you can just create your custom driver that uses a single tab (you would need either open it and keep, or find it by some criteria).

**Comment by acco** [comment]
That's exactly the direction I needed. Thanks @ziflex !

**Comment by ziflex** [comment]
Forgot to mention.
[Here](https://github.com/MontFerret/ferret/blob/master/cli/options.go#L26) is how you can register custom driver.
Your custom driver must implement ``drivers.Driver`` [interface](https://github.com/MontFerret/ferret/blob/ad24814efdc1264ff43b41b5461f74362dbd25c7/pkg/drivers/driver.go#L18) that has ``.Name`` method. This method is used during driver registration and then later you can use the name in your queries:

```golang
query := fmt.Sprintf(`LET doc = DOCUMENT("%s", { driver: "my_driver" })
// work on document
`, url)
```

**Comment by acco** [comment]
Got it, thanks!

**Comment by acco** [comment]
I am so close @ziflex. I have my own driver that's re-using existing tabs in Chrome. As a last step, I just need to prevent the program from _closing_ a tab when it's done.

Any pointers on the best way to do this? It looks like this happens inside of Page:

https://github.com/MontFerret/ferret/blob/master/pkg/drivers/cdp/page.go#L303

Not sure if my best option is to just fork and comment that line out :)

**Comment by ziflex** [comment]
Ouch :)
In your new driver, you can create a wrapper struct that implements ``drivers.HTMLPage`` [interface](https://github.com/MontFerret/ferret/blob/master/pkg/drivers/value.go#L177) and overrides this ``Close`` method by copying the logic without closing a tab.
Just return the wrapper from ``Open`` method of your driver.
