### ISSUE TITLE
Download file with cookies and content-disposition: attachment

### ISSUE THREAD

**Issue by rapidleft** [MontFerret/ferret#540]
I'm trying to use ferret to log in to a site and download a csv report. The report requires the login cookies, is dynamically generated, and has a `Content-Disposition: attachment` header which forces Chrome to download, and not just display it.

Simplified FQL looks like this:
```
LET page = DOCUMENT("https://neato-site.example.com")
LET report_url = "https://neat-site.exmple.com/report_generator?date=20200601&format=csv"
INPUT(page, 'input[id="username"]', @username)
INPUT(page, 'input[id="password"]', @password)
CLICK(page, 'input[type="submit"]')
WAIT_NAVIGATION(page)
```
So far this works great, but now I want to download my file.

```
RETURN DOWNLOAD(report_url)
```

This downloads a not-logged-in error page, because I guess it doesn't have the cookies, so I tried this too:

```
NAVIGATE(page, report_url)
RETURN page.innerHTML
```

But this fails on the NAVIGATE with `net::ERR_ABORTED: NAVIGATE(page,url) at 38:0`.

Maybe fails because of the `Content-Disposition: attachment` header? Is there some other way to do what I want with ferret or am I out of luck?

**Comment by ziflex** [comment]
You can store cookies and then load them with a page:

Store:

```
LET page = DOCUMENT("https://neato-site.example.com", { driver: 'cdp' })
LET cookies = JSON_STRINGIFY(page.cookies)
// STORE SOMEWHERE

```

And use them:

```
LET cookies = //RESTORE
LET page = DOCUMENT("https://neato-site.example.com", {
    driver: 'cdp',
    cookies
})
```

**Comment by rapidleft** [comment]
Thanks for your reply @ziflex. To be clear, I'm just trying to do this in one fql file, I'm not looking to save/restore cookies across sessions, I just need to use the cookies to download a file, which `DOWNLOAD` doesn't seem to do.

I tried your suggestion:

```
// <login as above>
LET saved = JSON_STRINGIFY(page.cookies)
LET cookies = JSON_PARSE(saved)
LET csv = DOCUMENT(report_url, {
  driver: 'cdp',
  cookies
})
RETURN csv.innerHTML
```

But this fails with `invalid type: expected date_time or string, but got none: DOCUMENT(report_url,{driver:'cdp',cookies}) at 40:10`.

**Comment by ziflex** [comment]
```invalid type: expected date_time or string, but got none: DOCUMENT(report_url,{driver:'cdp',cookies}) at 40:10.```
That's a weird error.

Nevertheless, ``DOWNLOAD`` does not use CDP driver for its purpose, that's why your cookies get "lost". I think it might be a good feature and I'm planning to release 0.12 soon.

Meanwhile, you need to try to download it using ``IO::NET::HTTP::GET`` function:
```
LET pairs = (
	FOR c IN page.cookies
		RETURN c.name + '=' + c.value
)

LET headerValues = CONCAT_SEPARATOR("; ", pairs)

LET binaryResp = IO::NET::HTTP::GET({
    url: report_url,
    headers: {
        Cookie: headerValues
    }
})
```

**Comment by rapidleft** [comment]
Thanks, I think I can get thsi to work with IO::NET::HTTP::GET.

I would certainly love a feature like `DOWNLOAD(page, report_url)` if that's what you're thinking about implementing for 0.12. I will keep an eye out :)
