### ISSUE TITLE
How to save formatted content

### ISSUE THREAD

**Issue by 0x0f0f0f** [MontFerret/ferret#541]
Let's say that I want to save an article content while keeping dotted lists, text formatting etc..
I could save an element's inner HTML. What if I only want to keep text data and avoid divs/images/iframes etc...
Is there any way to export an element's content textual markdown?

**Comment by ziflex** [comment]
Hey, you can get inner text of your elements.

**Comment by 0x0f0f0f** [comment]
I am already saving the inner text. I was wondering if it is possible to extract formatted text without having to extract the inner html, parsing it and converting it to markdown.
