### ISSUE TITLE
STYLE_GET seems broken

### ISSUE THREAD

**Issue by PierreBrisorgueil** [MontFerret/ferret#546]
**Describe the bug**
Not sure because it's my first test on it but STYLE_GET seems broken 

**To Reproduce**
```
LET doc = DOCUMENT('https://news.ycombinator.com/', {
    driver: 'cdp',
    viewport: {
        width: 1920,
        height: 1080
    }
})


WAIT_ELEMENT(doc, '.storylink', 5000)

FOR el IN ELEMENTS(doc, '.title')
    RETURN STYLE_GET(el, 'font-family')
```

will return [{},{},{}...]

**Expected behavior**

font-family: Verdana, Geneva, sans-serif

**Screenshots**

**Desktop (please complete the following information):**
 - Version: 0.11.1

**Comment by ziflex** [comment]
Could you try it in 0.12?

**Comment by PierreBrisorgueil** [comment]
@ziflex hello, same result on my side with ycombinator example 

`[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]
`

example code checked quickly, seems good to me.

**Comment by d2bit** [comment]
Hi, I've took a look and seems to me it's the correct behaviour, as it's checking for the element styles.

@ziflex what do you think about adding `COMPUTED_STYLE_GET` to retrieve `window.getComputedStyles`?
So that all applied styles to an element will be inspected.

If you say so, I'll try to implement it.

**Comment by PierreBrisorgueil** [comment]
hoo, maybe you are right, I didn't even think about it, it is very rare to have properties directly on the element today, that would be a good idea 👍

**Comment by ziflex** [comment]
> Hi, I've took a look and seems to me it's the correct behaviour, as it's checking for the element styles.
> 
> 
> 
> @ziflex what do you think about adding `COMPUTED_STYLE_GET` to retrieve `window.getComputedStyle`?
> 
> So that all applied styles to an element will be inspected.
> 
> 
> 
> If you say so, I'll try to implement it.

Can we think about an optional 3rd parameter to [``STYLE_GET``](https://www.montferret.dev/docs/stdlib/html/#style_get)?

Also, we would need to add a new property to a HTML element.

**Comment by PierreBrisorgueil** [comment]
if you add this I would advise enabling this option by default

**Comment by ziflex** [comment]
I wonder what implications might be if we always return computed styles?

**Comment by davad** [comment]
I _think_ returning computed styles is the natural thing to do here. Most use-cases I can think of, you'd be interested in what styles are currently applied to an element.

The only use-case I can think for getting the style that's attached to a specific element would be UI testing (i.e. "assert that style X is attached to element Y"). Can anyone think of another use-case?

**Comment by ziflex** [comment]
Ok, I think the resolution would be this:
- ``STYLE_GET`` returns always computed values
- ``el.style`` - returns computed values
- ``el.attributes.style`` - returns styles defined in the element.

**Comment by PierreBrisorgueil** [comment]
seems good !

**Comment by ziflex** [comment]
@d2bit do you wanna take it?

**Comment by PierreBrisorgueil** [comment]
Thx :)
