### ISSUE TITLE
how to scroll and scrape

### ISSUE THREAD

**Issue by rsinghtc** [MontFerret/ferret#547]
Hi,

I have a situation where webpage is showing data only when it gets scrolled . If I don't scroll I am able to fetch first few visible elements , how do I scroll and fetch all the elements ? I tried using Scroll functions like SCROLL_ELEMENT etc , but an example will be helpful .

Regards
RS

**Comment by PierreBrisorgueil** [comment]
Hello, 

```
LET doc = DOCUMENT('URL', {
    driver: 'cdp',
    viewport: {
        width: 1920,
        height: 1080
    }
})
SCROLL_ELEMENT(doc, 'SELECTOR')
```

there is also : 

https://github.com/MontFerret/ferret/blob/master/pkg/stdlib/html/scroll_xy.go
https://github.com/MontFerret/ferret/blob/master/pkg/stdlib/html/scroll_top.go
https://github.com/MontFerret/ferret/blob/master/pkg/stdlib/html/scroll_bottom.go

if it's for infinite scroll website you need to think about this like an infinite pagination
https://github.com/MontFerret/ferret/blob/master/examples/pagination_uncontrolled.fql

**Comment by rsinghtc** [comment]
I have tried that earlier , but it doesn't seems to work . For example  [dynamic_example](https://github.com/MontFerret/ferret/blob/master/examples/dynamic-page.fql) will just scrape first 20 songs , however if you scroll down , page has a total of 50 songs . I tried below code but it doesn't helps: 

`LET doc = DOCUMENT('https://soundcloud.com/charts/top', { driver: "cdp" })

WAIT_ELEMENT(doc, '.chartTrack__details', 5000)

SCROLL_ELEMENT(doc, '.chartTrack__details',{
    behavior: '1',
    block: 'end',
})

LET tracks = ELEMENTS(doc, '.chartTrack__details')

FOR track IN tracks
    RETURN {
    	artist: TRIM(INNER_TEXT(track, '.chartTrack__username')),
    	track: TRIM(INNER_TEXT(track, '.chartTrack__title'))
    }`

Even after adding scroll_element it still scrapes just the first 20 songs . I even tried scroll_bottom , but that too didn't helped :( !

-RS

**Comment by PierreBrisorgueil** [comment]
You need to target the bottom element to display for trigger load

```
LET doc = DOCUMENT('https://soundcloud.com/charts/top', { driver: "cdp" })

WAIT_ELEMENT(doc, '.chartTrack__details', 5000)

LET result = (
    FOR page IN PAGINATION(doc, '.loading')
        LIMIT 10
            SCROLL_ELEMENT(doc, '.loading')
            WAIT(5000)
            RETURN ""
)

LET tracks = ELEMENTS(doc, '.chartTrack__details')

FOR track IN tracks
    RETURN {
        artist: TRIM(INNER_TEXT(track, '.chartTrack__username')),
        track: TRIM(INNER_TEXT(track, '.chartTrack__title'))
    }

```

**Comment by rsinghtc** [comment]
First of all , thank you so much for providing a working example on scroll , it helped me understand this stuff lot better . However in my case something is still not working , my code is not getting all the listings , I only get top 3 and last one . My question is how do you normally debug ferret , is there a way to see the devtools dom output that is rendered after certain action ?

**Comment by ziflex** [comment]
> First of all , thank you so much for providing a working example on scroll , it helped me understand this stuff lot better . However in my case something is still not working , my code is not getting all the listings , I only get top 3 and last one . My question is how do you normally debug ferret , is there a way to see the devtools dom output that is rendered after certain action ?

Unfortunately, there are no debugging tools at this moment. In the future, I'm planning to introduce a debugger and other tools for troubleshooting.
At this moment, Chrome Remote Debugger and ``PRINT`` function are your friends :)
