### ISSUE TITLE
ferret -version

### ISSUE THREAD

**Issue by PierreBrisorgueil** [MontFerret/ferret#548]
Hello !

just quick information, it seems like `ferret -version`return nothing on my side

Thx for everything :)

**Comment by ziflex** [comment]
How did you get Ferret? Did you compile it locally or downloaded a binary? What OS?

**Comment by PierreBrisorgueil** [comment]
hey, @ziflex 
Mac os Cataline
`go get github.com/MontFerret/ferret@v0.12.0`

**Comment by ziflex** [comment]
ahh, it won't work if you install it via ``go get``.
Version number is assign during compilation by executing either Makefile or GoReleaser command.

**Comment by PierreBrisorgueil** [comment]
Hoo ok, thx for the information, sorry for the time lost
