### ISSUE TITLE
Don't stop script execution on non HTTP 200 

### ISSUE THREAD

**Issue by JekRock** [MontFerret/ferret#553]
**Is your feature request related to a problem? Please describe.**
Currently, there are services that secure website from automation tools like ferret. Some of them send 405 in response to the DOCUMENT function call that make a ferret script fail with an error even though a page is available (not the original page, but usually a page with the captcha).

**Describe the solution you'd like**
It would be nice to either have some kind of flag that will tell ferrret to ignore response codes and continue the script execution or to pass response codes to ignore as a parameter to the DOCUMENT function, for exemple.

**Additional context**
For the example with the captcha above, the script could have contunued the execution and wait for someone solving the captcha manually (in non-headless browser). It can be achieved by just calling a "wait for element" function.

**Comment by ziflex** [comment]
Hey, could you provide some links as examples?

**Comment by JekRock** [comment]
Sure. Try [this](https://www.g2.com/categories) one.
It will very quickly open the page with captcha when you start to do anything with the page

**Comment by ziflex** [comment]
hey, are you using CDP driver or in-memory one?
I see that Chrome handles these kind of pages.

**Comment by JekRock** [comment]
I was using the CDP driver

**Comment by ziflex** [comment]
What Chrome version?

**Comment by ziflex** [comment]
I'm trying to reproduce it with CDP driver, but it's working fine.
Could you give me more information?

**Comment by ziflex** [comment]
I added support to HTTP (InMemory) driver, but I don't see that it needs to be added to CDP.
Feel free to re-open.
