### ISSUE TITLE
Operator =~ not working with FILTER

### ISSUE THREAD

**Issue by noandrea** [MontFerret/ferret#555]
**Describe the bug**
Filtering with the =~ operator doesn't work 

**To Reproduce**

```
LET doc = DOCUMENT("https://www.amazon.de/gp/product/B0172JEA7K")
LET meta = ELEMENT(doc, '[data-automation-id="meta-info"]')

FOR a IN ELEMENTS(meta, 'a')
	FILTER a.attributes.href =~ "atv_dp_pd_star"
	RETURN TRIM(a.innerHTML)

```
returns
```
{
    "error": "compile query: invalid token: FILTERa.attributes.href=~\"atv_dp_pd_star\""
}
```

**Expected behavior**

Expected the list of names with the url matching `atv_dp_pd_star`

**Desktop (please complete the following information):**
 - Version v0.12.0

**Additional context**
TBH I am not sure if this is a bug or it is expected to work this way. But what is the use case of the =~ operator if it cannot be used in the FILTER expression?

**Comment by d2bit** [comment]
HI @ziflex 
I've created a PR to fix this. #558
