### ISSUE TITLE
How to download full page source?

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [MontFerret/ferret#561]
I checked the examples and it seems all of them are scraping part of the webpage. How to download the full page source to a file from scraped URLs? Thanks.

**Comment by PierreBrisorgueil** [comment]
hello @0x7FFFFFFFFFFFFFFF,  just return your doc var 👍  (you can play with INNET_HTML to select a part)

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thank you!
