### ISSUE TITLE
Doc.url not updated in case of Ajax navigation

### ISSUE THREAD

**Issue by PierreBrisorgueil** [MontFerret/ferret#577]
Hello,

If you click on a link managed with JS like AJAX, WAIT_NAVIGATION failed, we can simply wait for the update thanks to a WAIT_ELEMENT. But in this case, doc.url is not properly updated.

**Comment by ziflex** [comment]
hey, thanks for the report. 
could you provide a website and query?

**Comment by PierreBrisorgueil** [comment]
Yep, I have already sent you everything to test the buh in mp on ferret discord 👌

**Comment by PierreBrisorgueil** [comment]
@ziflex Thx ! I will test it soon ! :)
