### ISSUE TITLE
RAND(0,100) always same result

### ISSUE THREAD

**Issue by PierreBrisorgueil** [MontFerret/ferret#578]
Hey @u5surf  @ziflex 

since https://github.com/MontFerret/ferret/issues/483  and https://github.com/MontFerret/ferret/commit/7d7253325e7e465f16c47469b777799931987a8a RAND() seems to be ok 
but RAND(0,100) always return the same value also

Thank for everything

**Comment by u5surf** [comment]
@PierreBrisorgueil 
https://github.com/MontFerret/ferret/blob/master/pkg/runtime/core/helpers.go#L48-L49
It occur the same problem that has not given the rand.Seed. Thus it is easy and clearly to fix. I'll do that.

**Comment by PierreBrisorgueil** [comment]
Not to stale ☺️
