### ISSUE TITLE
Lacking documentation

### ISSUE THREAD

**Issue by mvrozanti** [MontFerret/ferret#582]
First of all, I think this project to be a great idea. Scraping really feels too repetitive and redundant at times with general-purpose languages.

Now, I'm trying to running ferret for the first time and it's been... hard.

I for one would like to have seen authentication-like-scenario example on the beginning of README. I think many times people actually wanna scrape things behind login walls and will try to use cookies for this. I then took to the documentation to find out if this was possible, only to be met with *absolutely* no mention of cookies in it. Okay. I then proceed to see if I can find any in the examples. No results. Gladly I went through the issues and found #242 , but still had no way of using this feature.

So, since there are no ways to loading cookies, I felt like I had to use the cdp protocol to actually login to the website I wanted to use cookies to get in. First impression, README is in conflict with `ferret -h` (which, by the way, is output to stderr for some reason?):

```
Usage of ferret:
  -cdp string
        set CDP address
  -cdp-keep-cookies
        keep cookies between queries (i.e. do not open tabs in incognito mode)
  -cdp-launch
        launch Chrome
  -help
        show this list
  -param value
        query parameter (--param=foo:\"bar\", --param=id:1)
  -proxy string
        address of proxy server to use (only applicable to static pages, proxy for dynamic pages controlled by Chrome)
  -time
        show how much time was taken to execute a query
  -user-agent string
        set custom user agent. '*' triggers UA generation
  -version
        show REPL version
```

Conflicts with `--cdp`, `--cdp-launch` and `--cdp-keep-cookies`. What's correct? I wonder if these are the only examples in conflict.

I now need to try both variants of these options to see *if* I can get cdp to work, so I continue and download [ferret's chromium docker image](https://github.com/MontFerret/ferret#environment) and go on to [this section](https://github.com/MontFerret/ferret#browser) to run this "Chrome" browser, which now makes me uncertain if I'm actually running Chrome or chromium

In `Linux 5.9.14-arch1-1`, `chrome` is not added to `$PATH` as [the environment section](https://github.com/MontFerret/ferret#environment) of the README seems to suppose.

Okay, maybe I should just follow along in the [browser-mode section](https://github.com/MontFerret/ferret#browser-mode) and run `ferret --cdp http://127.0.0.1:9222`, right? Well, not really. The line below this command states:

-------

**NOTE:** By default, ```ferret``` will try to use this local address as a default one.
You only need to explicitly pass the parameter if you are using a different port number or remote address.

-------

I tried running `ferret --cdp http://127.0.0.1:9222`, got no errors (maybe it's working?). Tried running `ferret --cdp http://127.0.0.1:0`, still no errors. There's clearly no actual check if cdp is up and running. Let's follow this **BOLD** note and omit `--cdp`'s argument, `ferret --cdp` (and `ferret -cdp`, of course). Output for both commands is: `flag needs an argument: -cdp`. 

My question is: how do I use ferret?

EDIT: By the way, even though the first line of FQL in [browserless mode](https://github.com/MontFerret/ferret#browserless-mode) doesn't need cdn, it fails with the following (duplicated) error message:

```
Welcome to Ferret REPL 0.13.0
Please use `exit` or `Ctrl-D` to exit this program.
> LET doc = DOCUMENT('https://news.ycombinator.com/')
line 1:51 extraneous input '<EOF>' expecting {And, Or, 'FOR', 'RETURN', 'DISTINCT', 'FILTER', 'SORT', 'LIMIT', 'LET', 'COLLECT', SortDirection, 'NONE', 'NULL', BooleanLiteral, 'USE', 'INTO', 'KEEP', 'WITH', 'COUNT', 'ALL', 'ANY', 'AGGREGATE', 'LIKE', Not, 'IN', Identifier, NamespaceSegment}
Failed to parse the query
extraneous input '<EOF>' expecting {And, Or, 'FOR', 'RETURN', 'DISTINCT', 'FILTER', 'SORT', 'LIMIT', 'LET', 'COLLECT', SortDirection, 'NONE', 'NULL', BooleanLiteral, 'USE', 'INTO', 'KEEP', 'WITH', 'COUNT', 'ALL', 'ANY', 'AGGREGATE', 'LIKE', Not, 'IN', Identifier, NamespaceSegment} at 1:51
```

**Comment by ziflex** [comment]
Hey, thanks for giving Ferret a try and sorry that you've experienced these confusion and problems. Indeed, the documentations is very far from being consistent, clear and broad. Hopefully, it will change.

Let me help you with your issues.


> I for one would like to have seen authentication-like-scenario example on the beginning of README. I think many times people actually wanna scrape things behind login walls and will try to use cookies for this. I then took to the documentation to find out if this was possible, only to be met with _absolutely_ no mention of cookies in it. Okay. I then proceed to see if I can find any in the examples. No results. Gladly I went through the issues and found #242 , but still had no way of using this feature.

That's a really good idea, thanks! I will add it to the list. You see, as a creator, I might not always know what needs to be explained. I guess, I need to create a poll to figure it out.


> So, since there are no ways to loading cookies, I felt like I had to use the cdp protocol to actually login to the website I wanted to use cookies to get in. First impression, README is in conflict with `ferret -h` (which, by the way, is output to stderr for some reason?):

``cdp`` is just a protocol to control browser (Chromium/Chrome) via WebSocket connection. That's it. You can load cookies, but you need to do it in your [code](https://github.com/MontFerret/ferret/blob/master/e2e/tests/dynamic/doc/cookies/load_with.fqlx).

> 
> ```
> Usage of ferret:
>   -cdp string
>         set CDP address
>   -cdp-keep-cookies
>         keep cookies between queries (i.e. do not open tabs in incognito mode)
>   -cdp-launch
>         launch Chrome
>   -help
>         show this list
>   -param value
>         query parameter (--param=foo:\"bar\", --param=id:1)
>   -proxy string
>         address of proxy server to use (only applicable to static pages, proxy for dynamic pages controlled by Chrome)
>   -time
>         show how much time was taken to execute a query
>   -user-agent string
>         set custom user agent. '*' triggers UA generation
>   -version
>         show REPL version
> ```
> 
> Conflicts with `--cdp`, `--cdp-launch` and `--cdp-keep-cookies`. What's correct? I wonder if these are the only examples in conflict.

``cdp`` is just an address of your open in debug mode browser. 

``cdp-launch`` tells Ferret to open locally installed Chrome/Chromium in debug mode. `

``cdp-keep-cookies`` instructs Ferret to open new tabs in regular mode, since by default it opens in incognito mode, in order to make every execution ``clean``, i.e. without state of previous queries. The naming could be confusing, agree.

> 
> I now need to try both variants of these options to see _if_ I can get cdp to work, so I continue and download [ferret's chromium docker image](https://github.com/MontFerret/ferret#environment) and go on to [this section](https://github.com/MontFerret/ferret#browser) to run this "Chrome" browser, which now makes me uncertain if I'm actually running Chrome or chromium
> 
> In `Linux 5.9.14-arch1-1`, `chrome` is not added to `$PATH` as [the environment section](https://github.com/MontFerret/ferret#environment) of the README seems to suppose.

Chrome or Chromium is basically the same, at least for Ferret.
If you run Chromium in a Docker container, then you do not need to use ``cdp-launch`` flag, since Ferret tries to find _locally_ installed Chrome/Chromium (I think this feature is not working on Windows). Personally, I rarely use this feature, so I might need to revisit it.


> Okay, maybe I should just follow along in the [browser-mode section](https://github.com/MontFerret/ferret#browser-mode) and run `ferret --cdp http://127.0.0.1:9222`, right? Well, not really. The line below this command states:
> 
> **NOTE:** By default, `ferret` will try to use this local address as a default one.
> You only need to explicitly pass the parameter if you are using a different port number or remote address.
> 
> I tried running `ferret --cdp http://127.0.0.1:9222`, got no errors (maybe it's working?). Tried running `ferret --cdp http://127.0.0.1:0`, still no errors. There's clearly no actual check if cdp is up and running. Let's follow this **BOLD** note and omit `--cdp`'s argument, `ferret --cdp` (and `ferret -cdp`, of course). Output for both commands is: `flag needs an argument: -cdp`.

For that, you need to launch Chrome/Chromium with remote debugging port as it's explained in [here](https://github.com/MontFerret/ferret#environment). The flag is needed only in cases if you are connecting to a running Chrome/Chromium on either different port or remote machine.

> 
> My question is: how do I use ferret?


- Write query
- Launch Chrome/Chromium with remote debugging port as described [here](https://github.com/MontFerret/ferret#environment)
- Execute query with ``ferret`` binary

> 
> EDIT: By the way, even though the first line of FQL in [browserless mode](https://github.com/MontFerret/ferret#browserless-mode) doesn't need cdn, it fails with the following (duplicated) error message:
> 
> ```
> Welcome to Ferret REPL 0.13.0
> Please use `exit` or `Ctrl-D` to exit this program.
> > LET doc = DOCUMENT('https://news.ycombinator.com/')
> line 1:51 extraneous input '<EOF>' expecting {And, Or, 'FOR', 'RETURN', 'DISTINCT', 'FILTER', 'SORT', 'LIMIT', 'LET', 'COLLECT', SortDirection, 'NONE', 'NULL', BooleanLiteral, 'USE', 'INTO', 'KEEP', 'WITH', 'COUNT', 'ALL', 'ANY', 'AGGREGATE', 'LIKE', Not, 'IN', Identifier, NamespaceSegment}
> Failed to parse the query
> extraneous input '<EOF>' expecting {And, Or, 'FOR', 'RETURN', 'DISTINCT', 'FILTER', 'SORT', 'LIMIT', 'LET', 'COLLECT', SortDirection, 'NONE', 'NULL', BooleanLiteral, 'USE', 'INTO', 'KEEP', 'WITH', 'COUNT', 'ALL', 'ANY', 'AGGREGATE', 'LIKE', Not, 'IN', Identifier, NamespaceSegment} at 1:51
> ```

By default, REPL immediately executes every line on ``Enter``. In ``README``, there is ``%`` used in order to write multi-line query. This is a valid error, since it's an incorrect query. Each query must end with either ``RETURN`` or ``FOR-IN`` statements.

**Comment by mvrozanti** [comment]
Thanks for clarifying some points and sorry if I sounded like a jerk. I'm gonna try and test a query after authenticating with chromium running as described in the environment section.

**Comment by ziflex** [comment]
No worries, you are fine. If you have any further questions, feel free to open a new issue or [join our Discord channel](https://discord.gg/kzet32U).
