### ISSUE TITLE
Confused about "quick-start"

### ISSUE THREAD

**Issue by zhichuanxun** [MontFerret/ferret#59]
After I install ferret by
> go get github.com/MontFerret/ferret

It's seems didn't work by just type  `ferret `
<img width="444" alt="screen shot 2018-10-06 at 3 54 33 pm" src="https://user-images.githubusercontent.com/19663277/46568954-28a99780-c980-11e8-86ad-c4e3278d8521.png">
However.It works by 
>  go run ./main.go
<img width="439" alt="screen shot 2018-10-06 at 4 00 33 pm" src="https://user-images.githubusercontent.com/19663277/46569000-fc424b00-c980-11e8-928c-bd4fdcafb82c.png">
Am I not install it correctly?

**Comment by SumLare** [comment]
Do you have these kind of lines in your ~/.bash_profile or somewhere else?
```
export GOPATH="$HOME/go"
export PATH="$PATH:$GOPATH/bin"
```
