### ISSUE TITLE
Implement string functions

### ISSUE THREAD

**Issue by ziflex** [MontFerret/ferret#6]
- [x] FIND_FIRST(text, search, start, end) → position
- [x] FIND_LAST(text, search, start, end) → position
- [x] JSON_PARSE(text) → value
- [x] JSON_STRINGIFY(value) → text
- [x] LEFT(value, length) → substring
- [x] LENGTH(str) → length
- [x] LIKE(text, search, caseInsensitive) → bool
- [x] LOWER(value) → lowerCaseString
- [x] LTRIM(value, chars) → strippedString
- [x] REGEX_TEST(text, search, caseInsensitive) → bool
- [x] REGEX_REPLACE(text, search, replacement, caseInsensitive) → string
- [x] REVERSE(value) → reversedString
- [x] RIGHT(value, length) → substring
- [x] RTRIM(value, chars) → strippedString
- [x] SPLIT(value, separator, limit) → strArray
- [x] SUBSTITUTE(value, search, replace, limit) → substitutedString
- [x] SUBSTRING(value, offset, length) → substring
- [x] UPPER(value) → upperCaseString

**Comment by okzapradhana** [comment]
Hello! thanks for providing `string` helpers. I just tried using `REGEX_REPLACE` function but it doesnt work. It says `not found function`. Is there any clue regarding this problem?
![image](https://user-images.githubusercontent.com/22886492/73336134-9b403400-42a3-11ea-9d20-475618ba8023.png)
