### ISSUE TITLE
Allow outer shebangs so FQL files can be used as scripts

### ISSUE THREAD

**Issue by ngirard** [MontFerret/ferret#603]
Hey,
let me start by expressing my gratitude for your efforts into this nice project !

Correct me if I'm wrong, but I think Ferret is greatly overlooked for front-end testing of Web applications... it might bring more visibility to describe it as suitable for *both* web scrapping and testing, what do you think ?

Anyway, I'm intending to use it for front-end testing in my current project. What I have in mind is to write each test as a set of FQL instructions, and to organize the tests themselves as targets in a justfile file, i.e. leveraging [Just](https://github.com/casey/just) which is, in a nutshell, a build automation tool with a simple syntax.

A great addition to this workflow would be the ability for Ferret to consider FQL files as scripts. This would allow my justfile to look like:

```sh
test1:
    #!/usr/bin/env ferret
    LET doc=DOCUMENT('xxxxx')
    .....

test2:
    #!/usr/bin/env ferret
    LET doc=DOCUMENT('xxxxx')
    .....

tests: test1 test2
```

Incidentally, Just is capable of that, so I can provide you with [a link](https://github.com/casey/just/pull/393) so you figure out how it was implemented -- sorry for not being able to give you an example in Go, I'm more of a rustacean.

Well, I hope you'll consider adding this feature, and in any case I'd be interested in having your thoughts about it.
Cheers !

**Comment by ziflex** [comment]
[Here](https://github.com/MontFerret/ferret/blob/master/Makefile#L32) and [here](https://github.com/MontFerret/ferret/tree/master/e2e/tests) you can find how it's used.

I will write a blog post soon about it.

**Comment by ziflex** [comment]
I totally forgot that we *do* have an blog post about Lab - [check it out](http://localhost:1313/blog/say-hello-to-lab/).
Let me know if this helps or not.

**Comment by ngirard** [comment]
Ha ! Great post indeed, thanks ! I skipped it when it was published because I wasn't feeling much concerned back then, then totally forgot about it...
