### ISSUE TITLE
not found: function: 'T::EQUAL'

### ISSUE THREAD

**Issue by ngirard** [MontFerret/ferret#604]
Using latest precompiled binary on Ubuntu 20.04.
Using `T::EQUAL` in a query results in this error:
```
Failed to compile the query
not found: function: 'T::EQUAL'
```

This is a blocking problem for me.

**Comment by ziflex** [comment]
Hey,

Sorry for the inconvenience, this is a mistake in docs. It should be ``T::EQ``.
