### ISSUE TITLE
FQL editor

### ISSUE THREAD

**Issue by panakour** [MontFerret/ferret#613]
Is there any FQL editor with Syntax highlighting? I use a jetbrains plugin https://github.com/ArangoDB-Community/aql-intellij-plugin it's working fine but in some case 
![fql](https://user-images.githubusercontent.com/12927166/114137039-458a0180-9914-11eb-9d0b-c4658168b854.png)
I've got syntax highlighting error

**Comment by PierreBrisorgueil** [comment]
Hey, you can have a look on AQL highlighter

**Comment by panakour** [comment]
Hi, AQL highlighter is what I was mentioned above.

**Comment by PierreBrisorgueil** [comment]
ho, ok sorry, I was too quick, there is no alternative at the moment I think
