### ISSUE TITLE
Find URL of the document after navigation 

### ISSUE THREAD

**Issue by aravindajju** [MontFerret/ferret#627]
I am using CLICK to initiate a JavaScript function that submits a form.  After the page is refreshed, I could access the new document.  However, doc.url returns the older URL of the page before the refresh.  What is the best way to find out the new URL?

CLICK(doc, 'input[name="btnS"]')
WAIT_NAVIGATION(doc)
LET prices = ELEMENTS(doc,PriceSelector)
LET url = doc.url

**Comment by ziflex** [comment]
Hey,

what version are you using?

**Comment by aravindajju** [comment]
I was using v0.13.  Upgraded to v0.15 and it works fine.  Thank you.
