### ISSUE TITLE
Implement strings.Like()

### ISSUE THREAD

**Issue by ziflex** [MontFerret/ferret#65]
The function must check whether the pattern search is contained in the string text, using wildcard matching.

```aql
LIKE("cart", "ca_t")   // true
LIKE("carrot", "ca_t") // false
LIKE("carrot", "ca%t") // true

LIKE("foo bar baz", "bar")   // false
LIKE("foo bar baz", "%bar%") // true
LIKE("bar", "%bar%")         // true

LIKE("FoO bAr BaZ", "fOo%bAz")       // false
LIKE("FoO bAr BaZ", "fOo%bAz", true) // true
```

[Src](https://github.com/MontFerret/ferret/blob/master/pkg/stdlib/strings/like.go)
[Docs](https://docs.arangodb.com/3.4/AQL/Functions/String.html#like)

**Comment by SumLare** [comment]
Will try to provide PR for this one today if you don't mind
