### ISSUE TITLE
Scrapoxy

### ISSUE THREAD

**Issue by fabienvauchelles** [MontFerret/ferret#68]
Hello,

Could be interesting to integrate Scrapoxy (http://scrapoxy.io).

You can have your own distributed network of proxies.

A cool mixed feature should be the capacity of running a scenario with a specific proxy of the mesh proxy (you select the output node to have a scenario from the same outside IP).

Best regards,
Fabien.

**Comment by ziflex** [comment]
@fabienvauchelles hi, thanks for letting me know. It's pretty handy.
At this moment, Ferret does not support proxy, but there is [a dedicated issue](https://github.com/MontFerret/ferret/issues/19).
