### ISSUE TITLE
Ferret requests are concurrent or sequential

### ISSUE THREAD

**Issue by rahulsingh303** [MontFerret/ferret#699]
Hi,

In Ferret when we are scraping data in a FOR loop , is it doing sequentially or is it concurrent ? For eg, in this code https://github.com/MontFerret/ferret/blob/b3adea3622c6d103515efa1edd48d41a2d566073/examples/dynamic-page.fql , when we are scraping artists and tracks , is Ferret going through the list sequentially or concurrently ?

-Rahul

**Comment by ziflex** [comment]
Hey, Rahul!
Ferret processes everything sequentially. The language does not support parallelism (yet?).
