### ISSUE TITLE
Add numeric functions

### ISSUE THREAD

**Issue by ziflex** [MontFerret/ferret#7]
- [x] ABS(value) → unsignedValue
- [x] ACOS(value) → num
- [x] ASIN(value) → num
- [x] ATAN(value) → num
- [x] ATAN2(y, x) → num
- [x] AVERAGE(numArray) → mean
- [x] CEIL(value) → roundedValue
- [x] COS(value) → num
- [x] DEGREES(rad) → num
- [x] EXP(value) → num
- [x] EXP2(value) → num
- [x] FLOOR(value) → roundedValue
- [x] LOG(value) → num
- [x] LOG2(value) → num
- [x] LOG10(value) → num
- [x] MAX(anyArray) → max
- [x] MEDIAN(numArray) → median
- [x] MIN(anyArray) → min
- [x] PERCENTILE(numArray, n, method) → percentile
- [x] PI() → pi
- [x] POW(base, exp) → num
- [x] RADIANS(deg) → num
- [x] RAND() → randomNumber
- [x] RANGE(start, stop, step) → numArray
- [x] ROUND(value) → roundedValue
- [x] SIN(value) → num
- [x] SQRT(value) → squareRoot
- [x] STDDEV_POPULATION(numArray) → num
- [x] STDDEV_SAMPLE(numArray) → num
- [x] SUM(numArray) → sum
- [x] TAN(value) → num
- [x] VARIANCE_POPULATION(numArray) → num
- [x] VARIANCE_SAMPLE(array) → num

https://docs.arangodb.com/3.4/AQL/Functions/Numeric.html

**Comment by Nexuist** [comment]
I can take this if you want, @ziflex. I will try to submit a PR some point this week.
