### ISSUE TITLE
Post request and conversion to binary type

### ISSUE THREAD

**Issue by errshoff** [MontFerret/ferret#751]
Hi all!
I need to send a POST request from my script. This is example code:

```
LET req = {hello: "world"}
LET result = IO::NET::HTTP::POST({
	url: "https://httpbin.org/post",
	body: JSON_STRINGIFY(req),
	headers: {"Content-Type": "application/json"}
})

RETURN JSON_PARSE(TO_STRING(result))
```

But when:
$ ferret exec post.fql

I get the following error:
invalid type: expected [binary], but got string: .body: IO::NET::HTTP::POST({url:"https://httpbin.org/post",body:JSON_STRINGIFY(req),headers:{"Content-Type":"application/json"}}) at 3:13

And that's right...
But how do I convert string to binary?
I did not find such a function in the documentation

**Comment by Gusyatnikova** [comment]
Hello!

You can use to_binary function:
Let binaryBody = to_binary('"id"=15')

Hope it helps,
Natalia

**Comment by errshoff** [comment]
Does not work:
compile query: not found: function: 'TO_BINARY'

**Comment by 3timeslazy** [comment]
@errshoff didn't you try to pass just `req` instead of `JSON_STRINGIFY(req)`?

**Comment by errshoff** [comment]
@3timeslazy I tried. The result is the same:
invalid type: expected [binary], but got object

**Comment by Gusyatnikova** [comment]
You can try add by yourself somethign like this:
1. To pkg/stdlib/types file to_binary.go
`func ToBinary(ctx context.Context, args ...core.Value) (core.Value, error) {
	err := core.ValidateArgs(args, 1, 1)

	if err != nil {
		return values.None, err
	}

	val := args[0].String()

	return values.NewBinary([]byte(val)), nil
}`

2. To pkg/stdlib/types/tib.go add raw to RegisterLib func
`"TO_BINARY": ToBinary,`
3. In your script use 
`Let binaryBody = to_binary('"id"=15')
LET result = IO::NET::HTTP::POST({
	url: "https://httpbin.org/post",
	body: binaryBody,
	headers: {"Content-Type": "application/json"}
})
`

**Comment by leopku** [comment]
@Gusyatnikova thanks a lot.
