### ISSUE TITLE
param test broken?

### ISSUE THREAD

**Issue by esell** [MontFerret/ferret#77]
**Describe the bug**
It appears that line 47 might be broken in `pkg/runtime/core/param_test.go`. 

`pf, err = core.ParamsFrom(ctx)` is being run and the test assumes `err` is not nil. The results say otherwise :)

```
Failures:

  * /Users/esell/go/src/github.com/esell/ferret/pkg/runtime/core/param_test.go 
  Line 47:
  Expected '<nil>' to NOT be nil (but it was)!
``` 

**To Reproduce**
1. Go to `pkg/runtime/core`
2. Run `go test `
3. See error

**Expected behavior**
to pass

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: firefox
 - Version: 62.0.3

**Comment by ziflex** [comment]
@esell does it happen om the latest version?

**Comment by esell** [comment]
@ziflex i did a rebase this morning on the master branch which is when i caught it. i just pulled down this repo though and things are passing. doing a diff i can't see any changes between my fork and this repo so i'm not sure what is going on but it is likely on my end. sorry for the false alarm, will close this.
