### ISSUE TITLE
Add date functions

### ISSUE THREAD

**Issue by ziflex** [MontFerret/ferret#8]
- [x] NOW() -> datetime
- [x] DATE(str) → datetime
- [x] DATE_DAYOFWEEK(date) → weekdayNumber
- [x] DATE_YEAR(date) → year
- [x] DATE_MONTH(date) → month
- [x] DATE_DAY(date) → day
- [x] DATE_HOUR(date) → hour
- [x] DATE_MINUTE(date) → minute
- [x] DATE_SECOND(date) → second
- [x] DATE_MILLISECOND(date) → millisecond
- [x] DATE_DAYOFYEAR(date) → dayOfYear
- [x] DATE_LEAPYEAR(date) → leapYear
- [x] DATE_QUARTER(date) → quarter
- [x] DATE_DAYS_IN_MONTH(date) → daysInMonth
- [x] DATE_FORMAT(date, format) → str
- [x] DATE_ADD(date, amount, unit) → datetime
- [x] DATE_SUBTRACT(date, amount, unit) → datetime
- [x] DATE_DIFF(date1, date2, unit, asFloat) → diff
- [x] DATE_COMPARE(date1, date2, unitRangeStart, unitRangeEnd) → bool

**Comment by yiss** [comment]
I wanted to work on this issue, any more details would very helpful :)

**Comment by yiss** [comment]
@ziflex should be there any special formatting for dates?

**Comment by ziflex** [comment]
@yiss awesome!

1. Read [the documentation](https://docs.arangodb.com/3.4/AQL/Functions/Date.html)
2. Do not mutate values itself - return only new instances.
4. Here is [an example](https://github.com/MontFerret/ferret/tree/master/pkg/stdlib/strings) how to create function. I will merge my work on Array functions, that will be even better reference.

**Comment by ziflex** [comment]
@yiss here is a default layout
https://github.com/MontFerret/ferret/blob/master/pkg/runtime/values/date_time.go#L9

If you need it, you can make it public

**Comment by yiss** [comment]
Oh okay perfect, also @ziflex  I've added configuration for CircleCi but I get a problem in the tests, can you take a look at it? thank you
Link: https://circleci.com/gh/yiss/ferret/21

**Comment by ziflex** [comment]
@yiss try to sync your fork with the upstream.
Why are you setting up CircleCi? Issue with TravisCI has been already resolved, so there is no need to do anything with CI pipeline anymore.

**Comment by yiss** [comment]
@ziflex Oh I didn't see that my bad, alright so no need for it then.
