### ISSUE TITLE
Navigate timeouts when using hash navigation

### ISSUE THREAD

**Issue by davidderus** [MontFerret/ferret#85]
**Describe the bug**
The command `NAVIGATE` times out with dynamic apps using hash navigation.

If I'm loading a JS app relying on hash navigation, and then navigating to a route, Chrome will load the page but Ferret will not aknowledge it and will timeout.

**To Reproduce**
```shell
echo "LET doc = DOCUMENT('http://todomvc.com/examples/backbone', true)

WAIT_ELEMENT(doc, '.new-todo')

NAVIGATE(doc, 'http://todomvc.com/examples/backbone/#/completed')

RETURN true" > test.fql

ferret test.fql
```

The output will be:

```
Failed to execute the query
operation timed out: NAVIGATE(doc,'http://todomvc.com/examples/backbone/#/completed') at 5:0
```

**Expected behavior**

- The command should not fail as the page has been loaded in Chrome
- Ferret should continue

**Desktop**
 - OS: `macOS 10.12.6`
 - Browser: `alpeware/chrome-headless-trunk` with `Chromium 71.0.3572.0`
 - Version: 65a7f2a2dfee81fe2299dea9225cad6c1819f252

**Comment by ziflex** [comment]
@davidderus hi!
Yes, I guess I know why it happens. Looks like 'load' event does not get fired during this navigation.
We may add a 2nd optional parameter to ``NAVIGATE(url [,wait])`` which would force Ferret to not wait for ``load`` event from the browser. And then, you could just use ``WAIT_ELEMENT`` function.

In your particular example, you could just click the button with the following code: ``CLICK(doc, "body > section > footer > ul > li:nth-child(3) > a")``.

**Comment by davidderus** [comment]
Yes, it works fine with `CLICK` and I'll use it for now.

I guess your suggestion for `NAVIGATE` could do the job and the timeout of `WAIT_ELEMENT` (_or its default value_) could be a good replacement for the navigate wait time in this specific case.

**Comment by ziflex** [comment]
@davidderus great! I would hold off the change of ``NAVIGATE`` until we get more use cases when it would be the only way to solve a problem.
