### ISSUE TITLE
elements selector doesn't support :visible

### ISSUE THREAD

**Issue by flazx** [MontFerret/ferret#86]
**elements css selector doesn't support :visible**

> LET doc = DOCUMENT("xxx")
> LET elems= ELEMENTS(doc, '.news_list li:visible')

And It will get nothing, but `LET elems= ELEMENTS(doc, '.news_list li')` is OK. How could I 
get the visible elements by the css selector?

**Comment by ziflex** [comment]
There are some bugs that may cause it (look at #80 and #42).
Other than that, I need more context to help you out. Could you give me a website you are working on?

**Comment by flazx** [comment]
The website is `http://rfb.hainan.gov.cn/xwdt/sxxw/1.htm`, and the `ELEMENTS(doc, ".news_list ul li.accbg")` not work as well which works in chrome console by `$(".news_list ul li.accbg")`.

> LET doc = DOCUMENT("http://rfb.hainan.gov.cn/xwdt/sxxw/1.htm")
> 
> LET lis = ELEMENTS(doc, ".news_list li:visible")
> 
> FOR li IN lis
>     LET url = ELEMENT(li, "a")
>     LET publishtime = ELEMENT(li, "span")
> 
>     RETURN {
>         title: TRIM(url.innerText),
>         memo: "",
>         url: url.attributes.href,
>         publishTime: TRIM(publishtime.innerText),
>         content: ""
>     }

**Comment by ziflex** [comment]
@flazx I see.
I have tested the web page and it seems the data gets loaded asynchronously which means you need to use dynamic document in the query.
Just change your document function call by adding a ``true`` value after the url:
```
LET doc = DOCUMENT("http://rfb.hainan.gov.cn/xwdt/sxxw/1.htm", true)
```

**Comment by flazx** [comment]
@ziflex Thank you for your help. I tried and it donesn't work as well. but It is not the ferret issue, It causes by The CSS specification doesn't define a :visible (or related) selector. [https://stackoverflow.com/questions/13388616/firefox-query-selector-and-the-visible-pseudo-selector](url)
