### ISSUE TITLE
Exit the Ferret

### ISSUE THREAD

**Issue by 3timeslazy** [MontFerret/ferret#92]
**Describe the bug**
Can't exit program using exit

**To Reproduce**
1. Run Ferret
```sh
$ ferret
```
2. You will see the following.
```
Welcome to Ferret REPL
Please use `exit` or `Ctrl-D` to exit this program.
>
```
3. Enter ```exit```
```
> exit
line 1:4 mismatched input '<EOF>' expecting '('
Failed to parse the query
mismatched input '<EOF>' expecting '(' at 1:4
```
4. Ok, enter ```exit()```
```
> exit()
line 1:6 extraneous input '<EOF>' expecting {'FOR', 'RETURN', 'LET', Identifier}
Failed to parse the query
extraneous input '<EOF>' expecting {'FOR', 'RETURN', 'LET', Identifier} at 1:6
```

**Expected behavior**
```
> exit()
3timeslazy@mbp $
```

**Screenshots**
<img width="583" alt="screenshot 2018-10-10 at 01 02 59" src="https://user-images.githubusercontent.com/23486601/46701884-e73c1500-cc29-11e8-8730-95e3a3a0c198.png">

**Desktop:**
 - OS: Mac OS

**Comment by ziflex** [comment]
[Fixed](https://github.com/MontFerret/ferret/commit/88188cac2c0c603d24377cd2b321f7cf9a2991e5)
