### ISSUE TITLE
Array and Object Deepcopy function

### ISSUE THREAD

**Issue by 3timeslazy** [MontFerret/ferret#95]
**Description.**
Method ```Clone``` of ```values.Array``` and ```values.Object``` does not copy these arrays and objects completely. Ex. If one of the elements of the array is an object and it will be changed from the outside, then the element of the array will be changed too. Test attached.
```go
Convey("Array Clone", t, func() {
		obj := values.NewObjectWith(values.NewObjectProperty("foo", values.NewString("bar")))

		arr := values.NewArrayWith(obj)
		clone := arr.Clone().(*values.Array)

		obj.Set(values.NewString("fizz"), values.NewString("buzz"))

		objFromClone := clone.Get(values.NewInt(0)).(*values.Object)

		So(objFromClone.Length(), ShouldEqual, 1)
		So(objFromClone.Compare(obj), ShouldNotEqual, 0)
	})
```

**Solution**
I propose to add method ```Deepcopy``` to arrays and objects, copying nested objects too.

**Comment by ziflex** [comment]
@3timeslazy hey, yeah, I know. It's done purposely to speed it up and do not allocate more memory than you need. 
The reason of that is that all functions from standard library do not mutate their arguments - they always return copies. It's risky, that's why we need more unit tests :)

**Comment by 3timeslazy** [comment]
@ziflex so the Deepcopy method is not needed? I just thought it would be useful in some object methods.

**Comment by ziflex** [comment]
@3timeslazy when I was adding ``Copy`` method to the ``Value`` interface I was thinking of adding ``deep: bool`` value in order to inform the object whether to perform a deep copy.
That could be a solution.

**Comment by 3timeslazy** [comment]
@ziflex by ```Copy``` you mean ```Clone```? I can implement it. Or I can implement ```Deepcopy``` only inside package ```pkg/stdlib/objects```. Which one is better?

**Comment by ziflex** [comment]
@3timeslazy my bad, yeah ``Clone`` :)
I would go with the param approach, it's more consistent. Because, we have Array which also might need to do deep copy. But it's more changes as well.

**Comment by 3timeslazy** [comment]
@ziflex but be better if I add new method ```Deepclone``` into ```core.Value``` interface? Because ```Clone(deep bool)``` is useless for simple types such as ```values.Int``` or ```values.Bool```. Also ```Deepclone``` will not break compatibility.

**Comment by ziflex** [comment]
> @ziflex but be better if I add new method `Deepclone` into `core.Value` interface? Because `Clone(deep bool)` is useless for simple types such as `values.Int` or `values.Bool`. Also `Deepclone` will not break compatibility.

You are right.  In this case it also does not make sense to add it as a part of ``Value`` interface.
Probably, we can create a separate interface with ``DeepClone`` method.

Actually, I like how Rust handles it: they have ``Copy`` trait which does a shallow copy and ``Clone`` trait which does a deep copy.
We could follow this approach and rename ``Clone`` to ``Copy`` method in ``Value`` interface. And then add ``Cloneable`` interface with ``Clone`` method which woulbe be implemented by complex types like  ``Array`` and ``Object``.

**Comment by ziflex** [comment]
The project is still in flux so it's ok to make these big refactoring changes.  It's better to do now, than later when it gets more stable with some side libraries.
Just make sure that you are using a good refactoring tool :)
